### ISSUE TITLE
[5.0.0 June 5th SNAPSHOT] SwipeRefresh is below the first expanded Sticky Header

### ISSUE THREAD

**Issue by bornest** [davideas/FlexibleAdapter#104]
Hi! Thank you very much for the latest fixes, library has really improved in its usability!

Found a minor issue with the SwipeRefresh and Sticky Headers:

If the _first_ Sticky Header in the list is _expanded_,
when you initiate refresh with SwipeRefresh,
SwipeRefresh animation is displayed _below_ this header.

**Comment by davideas** [comment]
Hi @bornest, @mdtuyen already reported this issue (see #83).
I also reported in the release note of last Snapshot.

Actually this is a strange bug: it's caused by the layout position order and I resolved it, but I've discovered yesterday that moving the StickyHeader layout inside the SwipeRefreshLayout it is not possible anymore to drag items: SwipeRefresh circle is showing while dragging down.
I've added more comments in the xml showing this fact.

I don't know how to resolve it having dragging feature working as well. You can test it in the demo app by commenting/un-commenting the lines in the layout `fragment_recycler_view.xml`

**Comment by bornest** [comment]
OK, got it. Fortunately, I don't need dragging functionality right now.

Actually, maybe you could disable SwipeRefresh when entering the dragging mode,
and enabling it after you've finished dragging.
