### ISSUE TITLE
Issue with header when refresh and load

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#110]
I applied new version 7/7/2016 and see:
- When I disable header (ULSItem) with setDisplayHeadersAtStartUp(false) => refresh => ULSItem showed
- Load more item with expandable => seem to expandItemsAtStartUp not work. New item not expanded.

**Comment by davideas** [comment]
Hi @mdtuyen, for the first point, in the current build, I do not have that behavior: ULSItem is marked done in the Singleton and so cannot be displayed anymore, it is added in the `ExampleAdapter.updateDataSet()`, there's is a check if it has to be added or not. I think there's no issue.

The second point, for the moment, I removed the auto-expand in combination with loadMore, ie. all addItems: Developer has to manually expand new items.

**Comment by mdtuyen** [comment]
@davideas Thanks for your reply. I want to ask about sticky header in my project after i use new version of FlexibleAdapter Stickyheader have been disable. What is the condition of header to sticky ? enablesticky for Adapter, Header item extend of IHeader or anymore ?

And must i put adapter.expand(i) when I add element to position i of adapter to expand that item ?

**Comment by mdtuyen** [comment]
Hi @davideas, I want to ask some Layout Item to top of recyclerview and them don't change when refresh or load more. What is the best solution to implement it ?

**Comment by davideas** [comment]
@mdtuyen, I wrote it in the release note of the snapshot, to avoid the bugs you need to pass also a new paramter `true` to the `super` constructor of the ViewHolder for the _header_ view. This creates a new middle layout that will become sticky avoiding all those crashing bugs.

For the second question, if the layout remains fixed, it is not part of the RV, therefore the Adapter is not involved it's not an item but a simple layout on the top of the RV. It cannot be otherwise

**Comment by mdtuyen** [comment]
With second question I think it is same with header, footer of listview. In your demo, you need re add them when refresh or init data. Is there simpler solution ?

**Comment by davideas** [comment]
Yes there is!
You need to add that special header item to the collection before this is passed to the adapter, so that, the `animateTo` is able to recognize its presence and it doesn't change position.
Override `updateDataSet()` and before calling `super()` add the header item at position 0.

`animateTo` has been revisited, now it works quite well, but don't abuse it for large 500/1000+ items it makes 3 times the calculation to check if all items has to be removed/added/moved from the original list.
