### ISSUE TITLE
[5.0.0-b7] Sticky header glitch when header layout have height set to "wrap_content"

### ISSUE THREAD

**Issue by LaskoS07** [davideas/FlexibleAdapter#121]
When sticky header layout height is set to "wrap_content", strange behaviour occurs. While scrolling, when a header touches the top of the list, item below that header instantly moves under it. It's like the header height changes to 0dp, but it is rendered as usual.

When sticky header have known size, like 48dp, everything is ok.

**Comment by davideas** [comment]
Hello @LaskoS07, I've tried with wrap_content as you say, indeed I've reproduced it and I understood why... because the view content changes parent, at the swap, the original parent height becomes 0, this because of the wrap with no content.

I've add a new line in the method `StickyHeaderHelper.ensureHeaderParent()`:
``` java
private void ensureHeaderParent() {
	final View view = mStickyHeaderViewHolder.getContentView();
	mStickyHeaderViewHolder.itemView.getLayoutParams().height = view.getMeasuredHeight();
	...
}
```
For me with that new line the issue should be resolved.
Can you try?

**Comment by LaskoS07** [comment]
It's ok now, thank you :)
