### ISSUE TITLE
Remove adding alpha-animation for items by default.

### ISSUE THREAD

**Issue by yeryomenkom** [davideas/FlexibleAdapter#124]
I think it`s not good for flexiblity to add by default alpha animation for the item.
Maybe we can use some flag:  "enable/disable this option"?

**Comment by davideas** [comment]
Hi @yeryomenkom, thanks for your comment, unfortunately the Alpha animation is necessary as base for every other animation, otherwise you will see the item in it's natural position before the animation starts.
If alpha is 0, then you see the item correctly moving towards its natural position.
You can try it without by cloning the project, you will see.

**Comment by yeryomenkom** [comment]
ok. thanks for your answer. 
Can I somehow achive behavior where animations invokes only for the first time when item are showing?

**Comment by davideas** [comment]
Interesting point. I didn't add this feature. Please keep in mind that animation is working fine but not finalized yet. I think I can include a check for the current animated item <= the last visible item in the RV, and change to false the boolean for the animations automatically, to be done with a new boolean, `setEntryAnimationOnly(true)`, what do you think?

For the moment you can do achieve it by calculating the delay and put it in the postDelayed method of the RV:

``` java
mRecyclerView.postDelayed(new Runnable() {
	@Override
	public void run() {
		//This will ignore the reverse scrolling as well
		mAdapter.setAnimationOnScrolling(false);
	}
}, 1500L);//1.5'' should be enough cover the lag in the older phones.
```

**Comment by yeryomenkom** [comment]
I think it will be great.

**Comment by davideas** [comment]
I close this issue, I opened the #125 for the enhancement.
