### ISSUE TITLE
after called adapter.notifyDataSetChanged(),when scroll RV, some items move to right position from wrong position

### ISSUE THREAD

**Issue by 54binge** [davideas/FlexibleAdapter#127]
Hi,@davideas  as title, and have called `adapter.setAnimationOnScrolling(false).setAnimationOnReverseScrolling(false);`
can u help me!

![image](https://cloud.githubusercontent.com/assets/4814206/16444837/a4d6b14a-3e12-11e6-8c93-953c4d4d110a.png)

**Comment by davideas** [comment]
Hello @54binge, this movement is not part of Adapter scrolling animation, especially if the 2 methods you mention are set false (by the way it is useless to call `setAnimationOnReverseScrolling(false)`, because it is ignored by the false of `setAnimationOnScrolling()` as documented.

If you directly call `notifyDataSetChanged()` all animation are not performed at all, you should know this.
Is it grid or staggered?

Are you sure about the wrong position for these 2 items? which header they have?
You can also activate the logs and see what the Adapter is doing.

**Comment by plenzt** [comment]
after notifyDataSetChanged() called and scrolling bottom up, the item displayed in wrong position, the position became correct after release the finger.
![img_1787](https://cloud.githubusercontent.com/assets/10138825/16514216/1c947fec-3f9d-11e6-88d2-91d0647b5b22.JPG)
![img_1788](https://cloud.githubusercontent.com/assets/10138825/16514222/1fd66b3e-3f9d-11e6-94e6-502ef6b18a05.JPG)

**Comment by davideas** [comment]
This is due to the layout that the RV is applying. As you see they don't change position but fill the space automatically, otherwise you have the empty space right there. _This is a normal behavior_, I've read this in the StaggeredLayout but probably it also occurs with GridLayout.
