### ISSUE TITLE
filterItems() can execute asynchronously?

### ISSUE THREAD

**Issue by LuckHard** [davideas/FlexibleAdapter#133]
Hi @davideas,
I would like to ask filterItems () whether there is an asynchronous implementation of the method?
For example, when I filter 5000 data, if I use filterItems () directly, it will lead to ANR.
Adding asynchronous filtering will make the library more perfect, please think about it, thank you.

###### EDIT for backlog:
- [x] notifyDataSetChanged()
- [x] AsyncTask.

**Comment by davideas** [comment]
@LuckHard, thanks for your message.
I agree with this improvement, it can be split in 2: `notifyDataSetChanged()` and Async.

Currently `filterItems()` calls `animateTo()`, it calculates the _removal / addition / moving_, I can make the animation optional, calling `notifyDataSetChanged()` it will improve a lot only that, but Async will probably still help for high volume like yours.

I will try to add this option to be controlled by the user first, then I will check how I can introduce the Async in the Adapter, even if, in version 4.2.0 I removed Async, at that time it was a superfluous feature.

**Comment by davideas** [comment]
@LuckHard, please let me know if the addition I have done (use SNAPSHOT release) resolves the ANR, you can test with higher number as well, so you can give me a better feedback.

Async is still not in place.

**Comment by davideas** [comment]
@LuckHard, I'm trying to add Async processing, there are several problems to resolve.

1. **All** `notifyXXX()` methods cannot be called in Background because `Caused by: java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling`.
2. We need to stop the previous unfinished task before a new one can start.
3. New listener to notify the fact a background task is started and finished
4. `expandAll()` and `collaspeAll()` can eventually benefit of the Async processing, but same limitations will occur.

Any ideas?

**Comment by cordeveloper** [comment]
Could perform the filtering and removals/additions/moves, but instead of notifying from the async thread put together a queue of positions (or pairs, for moves). When the task is finished, pass the queues back to the UI thread and go through them to notify. Just a thought, not sure if it's super feasible. At the very least, you can do all filtering up until animateTo off the UI thread.

Would like to integrate this library into my project, but no async filtering makes it a non-starter unfortunately.

Would also be nice to have an additional hook into the filtering logic, in case we need to filter by something other than / in addition to a string. My application has search by string filtering in addition to categoric filtering, and I don't see a way to accomplish this with your library right away.

**Comment by davideas** [comment]
Hi @cordeveloper, a part the work already published with `notifyDataSetChanged()` which resolves already the speed of the filter, yesterday I worked on **experiments** branch where I committed it now the AsyncFilter as @LuckHard suggested: I created a queue of notifications (field of main class for the moment) to be executed in `onPostExecute()`.
I also made changes (where possible) to use HashSet instead of List, this made a big improvements itself, unfortunately I had to made option the move animation.
Now, basic functionality works very fine, just sometimes if you insert a text, then stop, then add more text, it doesn't notify the last text.

I tested with :100:000 items in the emulator, I think it's not bad:
```
10:58:02.225 5003-5003/D/MainActivity: onQueryTextChange newText: 7
10:58:02.435 5003-5098/I/FilterAsyncTask: doInBackground - started Filter
10:58:02.435 5003-5098/V/FlexibleAdapter: FilterItems with searchText=7
10:58:03.535 5003-5098/V/FlexibleAdapter: Animate changes! oldSize=100001 newSize=40951
10:58:04.917 5003-5098/V/FlexibleAdapter: calculateRemovals total out=59050
10:58:04.940 5003-5098/V/FlexibleAdapter: calculateAdditions total new=0
10:58:04.940 5003-5098/I/FilterAsyncTask: doInBackground - ended Filter
10:58:04.946 5003-5003/V/FlexibleAdapter: Performing 100001 notifications
10:58:05.401 5003-5003/D/MainActivity: onUpdateEmptyView size=40951
```

I'll create a Fragment only for big list with dynamic values and searchFilter, for now you can use `FragmentEndlessScrolling` and `FragmentExpandableSections` to test and give me some feedback. To test it, change the numbers directly from the initialization of the RV.
And from the `MainActivity` you can change the delay or remove it, to call `filterItems()`.

@cordeveloper, to Filter by categories etc, you can try to override `filterObject()` as I suggested in the method comment, you will tell me more.

**Comment by davideas** [comment]
I moved all code in **dev** branch. The demo Fragment for Async is ready (to be finilized), but you can already test with different configuration.
I wait your feedback.
Davide

**Comment by davideas** [comment]
The part 2 of this improvement (AsyncTask) is now published with the Snapshot release of today 16/7/2016.
