### ISSUE TITLE
Flexible adapter issue on removing items and also questions about consistency of approach used

### ISSUE THREAD

**Issue by yamelkaya** [davideas/FlexibleAdapter#141]
I am using FlexibleAdapter with sticky headers. I need to modify a list (add or remove items) on both sides (load more items on scroll and remove unused at the opposite side - infinite scroll). 

Example that illustrates the problem I have: I need to remove 1st 4 items (not counting headers) in the following list

**header1**
_item1 
item2
item3_                             
**header2**
_item1
item2_  
**header3**
_item1
item2_

so i call `removeRange(0,5)` to remove them but after that I have the following list          

_item2_  
**header3**
_item1
item2_
 
when I call `adapter.getSectionHeader(0)` I get the `null`.  So eventually adapter has items without header although item `getHeader()` returns proper header. 

I found API that allow to work with adapter inconsistent. Sometimes adapter did the work with headers for us  (I just set headers into items and adapter cares about the rest) and sometimes it doesn't (when executing `removeRange` it's delete headers and items and we need to keep in mind that headers already there) and I need to think about header management myself. So, I think there is should be a single approach in work with headers. Either user dealing with headers from the beginning an know they are in the list, or we dealing only with valuable items and headers work automatically. 

It is also quite confusing, that after I initialize adapter with items I can not get them (list of items) anymore. So, if I have e.g 5 items and 3 different headers eventually I have adapter with 8 items and I don't know their initial positions (only global - mixed with headers) and to get 1st real item (not header) I need to get all section headers, search the 1st header with not empty item set and then `get(0)`. Why such limitation exists?

**Comment by davideas** [comment]
@yamelkaya, well, the use case you described is something very specific, so a library cannot contextualize that. True that you don't know the positions, but you know the item references and from them you can obtain the positions!

You can do a very simple routine that skips the headers, indeed removeRange DOES removeRange for the positions of the adapter in that particular moment. So, no, you can't use remove range in the simple way with your use case, you need to customize a solution around it by extending the adapter and customize it around the use case.
There are several ways that reach your use case and delete only the correct items. There are also methods in the library that can support to write your custom routine, such as `isHeader()`, `hasHeader()`, `getSectionItems()`, etc... indeed you are managing sections

Please give a complete overview at the methods.
Also, and not less, the documentation (Wiki pages) describes 2 use cases, maybe you want have a look at the Expandables, that a part the name, it is a section with subItems that you can control in different way. Just disable the expandable feature.

Be aware that, I am in the middle for the next pre-release working on performances and others improvements, and that some methods will be reviewed for deprecation, not yet marked, just a TODO in the code (**dev** branch), so I suggest you take the current code and the SNAPSHOT to have the latest release without the latest bugs. Follow the issue 39.

For the moment I keep open this issue, so I can follow your case.
I hope I could answer at some of your questions.

**Comment by davideas** [comment]
Another thing, positions are too dynamic, they change too often for a specific item to follow, so the entire library relies on item references which exclude a lot of potential bugs. With the item reference you can always get the correct position for that item, you don't need to care where it is in that moment. 0 mistakes. `getGlobalPositionOf(item)` is a key method in this library.

**Comment by yamelkaya** [comment]
@davideas thanks for reply. If I understand you right my case with two side infinite scroll is not typical use case for your adapter and there is no easy way to update items (add or remove) but I suppose it's possible. Which strategy should I use to update items on start and in the end? For now I use the following:

1. Call `updateDataSet(items)` - to refresh all items in set
2. Call `addItems(0, items)` (items has headers) - to insert items at the start position
3. Call `addItems(getItemsCount(), items)` (items has headers) - to insert items at the end position
4. Call `removeRange(getItemsCount() - count, count)` - to remove items at the end position
5. Call `removeItem(index)` for all items (not headers) starting from 0 and after that remove empty headers - to remove items at the start position

Is it right? I noticed that sometimes I have troubles with list when I do this way - items appears without headers. When I call `notifyItemRangeChanged(0,getItemCount())` after `addItems(...)` or `removeRange(...)/removeItem(...)` this problem disappears. Is it correct solution or something missed?

**Comment by davideas** [comment]
Hi @yamelkaya, so 1 step per time.

- For a refresh you can call `updateDataSet(items, true)`. Where true will animate your changes by calling the specific `notifyItemXXX()` methods only for the items that need the call, so `notifyDataSetChanged()` is not called. In general never call it. In the last Snapshot I've made a big change when calling updateDataSet and Filter.

- Infinite scroll at bottom, it is supported, and you need to call the `onLoadMoreComplete()` at the right callback, for this specific use case better if you read the dedicated Wiki page.

- The infinite scroll at top you need to know in which section they belongs, because you need to know the exact position respecting the order in their section, for that I created a method `calculatePositionFor()` with a `Comparator` object, this comparator might appear complicated, take suggestion from my demoApp. You can also use `addItemToSection()`, etc...
It's not ok to add items at position 0 if these items already have a section displayed.

- Removing items and skipping the headers, you need to implement a custom method that skips the position if in that position there's a header. Be aware that if you refresh the list when headers are empty, those disappear from the adapter, they are displayed again automatically once you add the sectionableItem to the adapter using one of the method you desire.

Finally, don't call any of `notifyItemXXX()` adapter takes care about these calls.
Read the Wiki pages for Headers and Sections.
