### ISSUE TITLE
Group not change state with setAutoCollapseOnExpand(true)

### ISSUE THREAD

**Issue by rainboy93** [davideas/FlexibleAdapter#157]
First of all, incredible work bro :D.
I have a lot of groups (expandable section) and i set the adapter with param _setAutoCollapseOnExpand(true)_. Each group have 2 background color states: gray on expanded and white when collapsed. First i click on one group to expand it then i click to another group to expand it too. At that time the first group should collapse (this work nicely) but the state not change. It mean that the background color not change its state.
I fixed this by add _notifyItemChanged(position)_ in _expand_ and _collapse_ method of _FlexibleAdapter_ class. Just want you to know.
Again, incredible work bro. Sorry for my bad English.

**Comment by davideas** [comment]
Thanks for the message @rainboy93 
.
I think in this case, the `notifyItemChanged(position)` is specific for your use case, while others don't need this feature and because you can reach this behavior by simply extending the Adapter and override the appropriate methods. It seems more a customization than a general feature.
However, this can be better obtained in the expand/collapse of the `ExpandableViewHolder`, without calling the binding method.
