### ISSUE TITLE
Sticky headers causes bug when used with ViewPager.

### ISSUE THREAD

**Issue by zed13** [davideas/FlexibleAdapter#163]
Hi,
I run into bug, when I try to use same header for two different list in fragments. This header have some controls that perform different actions according to fragment. At first fragment header was invisible, and on other fragment header's controls launch inappropriate actions.
 
I found out that it's happens when adapter searching for sticky header container by  #this code:
`	public ViewGroup getStickySectionHeadersHolder() {
		return (ViewGroup) ((Activity) mRecyclerView.getContext()).findViewById(R.id.sticky_header_container);
	}`

**Comment by davideas** [comment]
Hi @zed13, for how the technique for sticky headers is made, the layout that holds the header when sticky must be in the fragment of the view pager, so that every time a new Fragment is created it has its own references to the instances of the _Sticky Layout_ for the specific `RecyclerView` instance only.

Not only, you need the main view that holds the fragment to search for the ID of that fragment, so the view can be found with no duplication. You should consider to override that method or maybe follow the issue #70.

I'm sorry but I did not experiment too much with `ViewPager`.
