### ISSUE TITLE
How can I use stickyHeader in NestedScrollView??

### ISSUE THREAD

**Issue by kwakseungkwon** [davideas/FlexibleAdapter#164]
StickyHeader doesnot work  in NestedScrollView.
because of stickyHeader cannot recevie onScrolled() listener.
How can I use stickyHeader in NestedScrollView??

```
xml code
<android.support.v4.widget.NestedScrollView
		android:id="@+id/scroll_view"
		android:layout_width="match_parent"
		android:layout_height="match_parent">
	<FrameLayout
		android:layout_width="match_parent"
		android:layout_height="match_parent">
    	<android.support.v7.widget.RecyclerView
			android:id="@+id/recycler_view"
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			tools:listitem="@layout/recycler_expandable_item"/>
		<include layout="@layout/sticky_header_layout"/>
	</FrameLayout>
</android.support.v4.widget.NestedScrollView>

```

**Comment by davideas** [comment]
Hi @kwakseungkwon, have you tried to remove `NestedScrollView` and use directly `RecyclerView`? RV can take place of NSV.
But I don't know how sticky layout might behave. Probably it needs a custom behavior.
Need some experiments.

**Comment by tprochazka** [comment]
Btw. This comment is not related to FlexbileAdapter, but we found on our project huge problem with NestedScrollView . When the RecyclerView is inside of the NestedScrollView it cause that all items in the adapter are rendered (view created). It looks like NestedScrollView  thing that its height is infinite. It is probably bug in NestedScrollViiew implementation. Maybe it was fixed in latest version we don't test it again.

**Comment by davideas** [comment]
Indeed, RecyclerView is already a scrolling view, so you don't need NestedScrollView. This was also showed in google examples.

**Comment by DavidCorrado** [comment]
I would be interested to see if you can look into this issue where you cant nest the recyclerview.  A specific use case I have is multiple recyclerviews wrapped by a nestedscrollview.  That does work the only problem is the sticky headers do not work with that.  From your sample code I found in the fragment_recycler_view.xml if you wrap a nestedscrollview inside the swiperefreshlayout it makes the sticky header not work.

I am not really sure why this is happening.  Can you look into if its a quick fix.  If its not can you tell me what to look into and I can work on possibly a pull request?

**Comment by davideas** [comment]
@DavidCorrado, android layouts works with unique id, so you need to specify for each RV which is its container for sticky headers. Recently, I've added a `set` method, to customize this container, please check the latest snapshot, (issue 39).
I guess, anyway, you have an horizontal layout for all RVs in the NestedScrollView.
More I can't help, you have to play with layouts.

**Comment by i-schuetz** [comment]
@tprochazka just for completeness - that problem is solved when you assign the recycler view a fixed height (or width).

**Comment by dhingrap** [comment]
@i-schuetz I'm using following library for sticky header with recyclerView
https://github.com/TellH/RecyclerStickyHeaderView/blob/master/README.md

and I'm also facing the issue of nesting stickyHeaderView with NestedScrollView.In this case headers are not getting sticked.I have to  use NestedScrollView because in my UI we have appbar layout over recyclerView.Your help will be really appreciated if you have find any solution for this.I have tried fixed the height of recyclerView but that didn't fix the problem.

**Comment by EliYakubov77** [comment]
Has anyone found a solution to this problem?
please

**Comment by astamato** [comment]
Has anyone found a solution to this problem?
