### ISSUE TITLE
Integration with RealmBasedRecyclerViewAdapter/RealmRecyclerview

### ISSUE THREAD

**Issue by ncioj10** [davideas/FlexibleAdapter#166]
Hi,
I am looking forward to implementing this library together the Realm database in background. My question would be, if there is a feature planned, that combines the [RealmBasedRecyclerViewAdapter](https://github.com/thorbenprimke/realm-recyclerview/blob/master/library/src/main/java/io/realm/RealmBasedRecyclerViewAdapter.java) and this Adapter, so that it is possible to have efficient loading on the one side combined with the excellent features of this library on the other side?

Thank you very much in advance!

Nicolas

**Comment by davideas** [comment]
Hi @ncioj10, from a first quick analysis I think this is somehow possible. There's a margin to create extensions for _Realm_ and _Firebase_ too! But, **I need to complete this phase of development first**, in order to think in the details these extensions.
The 2 extensions will be wrappers (still Adapter pattern) for my FlexibleAdapter.

I have seen that, the official Realm adapter example and the library you linked are _not_ very well made because they use widely the `notifyDataSetChanged()` method which is against the main principle of the RecyclerView. Yes, this function is at our disposal but as last chance, because it kills all the animations.

I put this issue as _enhancement_  with unknown milestone for now.

**Comment by ncioj10** [comment]
Hi @davideas ,
thank you for the quick reply! This would be indeed very helpful! 

I think the reason for these calls is, that Realm currently does not support fine grained notifications on what data exactly has changed, so finding that out is probably quite inefficient. This is something that occured to me as well, when I started to have a look at both of them. This is linked to this [issue](https://github.com/realm/realm-java/issues/989). The library I've linked has the possibility to animate updates, but from my experience that doesn't work very well.

**Comment by ajma** [comment]
I'm interested in seeing something like this for Firebase

**Comment by ajma** [comment]
Specifically something with this: https://github.com/firebase/FirebaseUI-Android/blob/master/database/src/main/java/com/firebase/ui/database/FirebaseRecyclerAdapter.java

**Comment by davideas** [comment]
@ajma, I still need to fix some behaviors, clean code from new deprecations and add new features before focusing on these extensions.
Currently my time is shorter than I thought.

Thanks for the link of that Adapter by the way.

**Comment by ncioj10** [comment]
Currently they are close to implementing fine grained notifications, which will make it a lot easier to update objects. https://github.com/realm/realm-java/issues/989

**Comment by davideas** [comment]
Realm integration has been committed in **extensions** branch, it has some bugs on deleting and long press items which I do not understand, specifically `java.lang.ArrayIndexOutOfBoundsException: rowIndex is less than 0` (Issue https://github.com/realm/realm-java/issues/2408).

More over and sadly, we can't use inheritance on the items yet (https://github.com/realm/realm-java/issues/761) until they redesign the Realm library, LOL(!): Until then user must extend every item from `RealmObject` and implement `IFlexible` every time. I see this a very bad.

**Comment by davideas** [comment]
Realm integration has been committed in **extensions** branch, it has some bugs on deleting and long press items which I do not understand, specifically `java.lang.ArrayIndexOutOfBoundsException: rowIndex is less than 0` (Issue https://github.com/realm/realm-java/issues/2408).

More over and sadly, we can't use inheritance on the items yet (https://github.com/realm/realm-java/issues/761) until they redesign the Realm library, LOL(!): Until then user must extend every item from `RealmObject` and implement `IFlexible` every time. I see this a very bad.

Fine graned notifications (https://github.com/realm/realm-java/issues/989) is also used.

**Comment by davideas** [comment]
Evaluating usage of `RealmFlexibleAdapter` as extension for FlexibleAdapter:
- As explained in issue (https://github.com/realm/realm-java/issues/761), an model object must extend `RealmObject` in order for Realm library to work. Should or shouldn't extend `IFlexible` items?
I think that `IFlexible` items are visual items while Realm objects are DB objects. This approach allow to separate the _presentation_ layer from _business / data_ layer and more over can allow the usage of the several features of this Adapter. On the other hand, if they remain the same instance, all model objects must implement `IFlexible` and features like Sections / Expandables / Headers have hard time to be used since the data structure is not compatible with the structure that FlexibleAdapter wants.
- What `RealmFlexibleAdapter` should automate? which abstract methods should have?

**Comment by davideas** [comment]
With the introduction of Android Architecture, Lifecycle and my [Livedata](https://github.com/davideas/FlexibleAdapter/wiki/Extensions-%7C-LiveData) extension, I decided to archive this Realm extension and to remove from the plan.
