### ISSUE TITLE
Why getHeaderItems() may return 0 just after adding new item? 

### ISSUE THREAD

**Issue by yamelkaya** [davideas/FlexibleAdapter#187]
I use `FlexibleAdapter` with sticky headers (SNAPSHOT). I faced with really strange behavior. When I add new item: 

`addItem(calculatePositionFor(item,comparator),item);`

`getItemCount()` returns _previous count + 1_ but `getHeaderItems()` returns empty list although I'am sure I set header for item. Unfortunately I haven't been able to reproduce this issue in unit tests yet (everything works as expected). I have it only when I run the real app. So, still looking a reason of the problem.   

Do you have any ideas why this may happen?

**Comment by davideas** [comment]
@yamelkaya, debugging might help, difficult to say. Basically you have the header in the returned list if `isHeader()` returns true for the item in the main list.

**Comment by yamelkaya** [comment]
I've checked `getHeaderItems()`. The problem is that when I call this method `mItems` has only items I insert but don't have their headers yet. 

By the way I noticed this problem when I start debugging. When I continue  app execution headers appear in list and everything seems working.

**Comment by yamelkaya** [comment]
Seems that the problem was in `headersShown` which was always `false` (even when I call  `setDisplayHeadersAtStartUp(true)`) until I set `setAnimationOnScrolling(true)` before. 

After that headers appears just after call `addItem`.

**Comment by davideas** [comment]
I changed that part since your last issue, but what you say is bit strange. However, read the comments of those methods.

**Comment by davideas** [comment]
@yamelkaya, just to advise you that I will produce a new SNAPSHOT soon, it will include the beta8 + a couple of fixes.

**Comment by yamelkaya** [comment]
@davideas I've checked a new SNAPSHOT and everything seems to be the same. I've updated previous demo project with sticky headers [FlexibleAdapterWithStickyHeadersDemo](https://github.com/yamelkaya/FlexibleAdapterWithStickyHeadersDemo). You may check it to see the issue. 

I have the following code in `StartActivityFragment `:

```
@Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        DatePicker datePicker = (DatePicker) getView().findViewById(R.id.date);
        DateTime now = DateTime.now().withTimeAtStartOfDay();
        datePicker.init(now.getYear(),now.getMonthOfYear() - 1, now.getDayOfMonth(),(picker,y,m,d) -> onDateChanged(picker,y,m,d));

        items = (RecyclerView) getView().findViewById(R.id.items);
        items.setLayoutManager(new SmoothScrollLinearLayoutManager(getContext(), LinearLayoutManager.VERTICAL, false));
        adapter = new AgendaFlexibleAdapter(new TaskDbProvider());
        items.setAdapter(adapter);
        adapter.reloadItems(new DateTime());

        loadItemsButton = getView().findViewById(R.id.loadItemsButton);
        loadItemsButton.setOnClickListener(v -> onLoadItemsClick(v));
    }

    private void onLoadItemsClick(View v) {
        adapter.reloadItems(DateTime.now().withTimeAtStartOfDay());
    }
```

So, I reload items in `onActivityCreated` and `onLoadItemsClick`. When I load items on click everything is OK. But When I load items on activity create and check headers count it is equal to 0. The issue mentioned above is reproduced without `setAnimationOnScrolling(true)` (I've commented this code in `AgendaFlexibleAdapter` constructor). 

```
 private AgendaFlexibleAdapter(@NonNull List<AgendaListItemVM> items, TaskDbProvider taskProvider) {
        super(items);
        //setAnimationOnScrolling(true);
        setDisplayHeadersAtStartUp(true);
        enableStickyHeaders();

        this.taskProvider = taskProvider;
    }
```

Sorry for overloaded example (I mean code in `AgendaFlexibleAdapter`). I am adding new items in `addItems` method (you may set debugger there)

```
    private void addItems(List<AgendaListItemVM> items) {
        for (AgendaListItemVM item : items) {
            addItem(calculatePositionFor(item),item);
        }
    }
```
Thanks for your attention to the issue.

**Comment by davideas** [comment]
I tried the demo project for at least 1h, but I'm trying to understand what is the original issue, you don't see the headers?
- I see the headers in the emulator and on my S3.
- `headersShown` is always true because is not covered by any `if` statement
- `getHeadersItems()` returns always an empty list in both cases, `setAnimationOnScrolling(true & false)` at startup and by clicking loading button. This because the list results empty.

Another thing very important, don't call methods as parameter for another method: very often that method, if in a cycle, it is executed every time (I'm referring to `Stream.of(getHeaderItems())`). Save the list in a variable and pass it to the method. In general, result of long operations should be saved in a variable, also you make the code easier to read for others :-)

Also, I remind you that headers are added based on the existing items in the Adapter list, if this list is empty, then no headers are returned.

**Comment by yamelkaya** [comment]
The code of FlexibleAdapter defenitely has a lot to improve :) I am sorry for that.

The original problem is that when I try to get headers just after call `adapter.reloadItems(new DateTime());` inside `onActivityCreated` it returns empty list although getItemCount() returns the number of inserted items (all items has headers). I see all the headers in list later (when click "continue") but I can't use them just after insertion. 

I don't understand why you say that lists empty. Do you mean that adapter doesn't have any data? I can not test it right now but I will check it one more time tomorrow morning. I also will try to simplify an example as much as possible to prevent a waste of your time.

**Comment by davideas** [comment]
Try to enable the logs `FlexibleAdapter.enableLogs(true)` before creating the Adapter. You will see lot of useful information. Then, I guess you already have read the javaDoc of the methods `setDisplayHeadersAtStartUp(boolean displayHeaders)`, `showAllHeaders()` and also `updateDataSet()`.

_Initialization_ should be done when you create the Adapter for the first time unless you receive the data from network (addition is delayed).
In any case you are not displaying Headers during the first initialization, your list is empty and you still want the headers to be displayed at startup:

- You can create your list when you receive the data, then call `updateDataSet()` or `addItems()` (effects are different even if the result is the same) and then show headers. I don't understand why you are adding items one by one to the Adapter if you created the list already (you can create with the order you want).
- `setDisplayHeadersAtStartUp()` is an action (I would like to rename it, as you can already see from the code), it must be in **Post** because you can even call `addItems()` after you call this method waiting some items to scan and show header. It _can't_ show anything and _can't_ set any flag if there aren't items in that moment, so being in post resolves this issue, of course you _can't_ retrieve the headers until the whole initialization is completed.
- You can eventually call `showAllHeaders()` (if you didn't before with `setDisplayHeadersAtStartUp()`) but at the end of the `addItems()`, of course "add animation" is triggered instead of the scrolling animation. I don't know why you are retrieving the headers from the Adapter if you have just created the list with those headers just a moment before...

I hope now things are clearer.

**Comment by yamelkaya** [comment]
> But, I don't know why you are retrieving the headers from the Adapter, if you have just created the list with those headers a moment before...

In some cases after loading items I need to scroll to particular position (item or header). When I try to find this position I get -1 for header (because it's not created yet) and of course scrolling doesn't work as expected (because I try to scroll to -1 element). 

I use data provider inside FlexibleAdapter because I thought that this is only place where items used and all required data I can get from adapter after that. But maybe I need additional caching for loaded items (together with headers) in order to access them quickly and not depend from adapter lifecycle.  

I understand that my code doesn't work because of using **Post**  inside `showAllHeaders` and definitely you have reasons for that but I can't understand them.

**Comment by davideas** [comment]
The reasons are explained in the 2nd point.
So you can eventually apply the solution in the 3rd point.

**Comment by yamelkaya** [comment]
So, I agree, that action like "adding headers" definitely should be after items inserted. And yes, if  I wrap my code, which calculating necessary item position into post it's work as expected. So from that point of view, I think, issue could be marked as resolved.

However, just from the development point of view, it's still a bit unclear for me, why you decide to select such execution model. Why not simply initialize necessary adapter state with flags and values (which is seems a like a good first guess for setDisplayHeadersAtStartUp will be) and than having single execution line which work according logic configured with this settings? Or in other case, made all of the stuff "synchronized" and use actions `addItems`, `displayHeaders` the way as they should be (like `displayHeaders` expected `addItems` called first). I think that every time when something added in "async" manner, it's just increase complexity and make the whole flow harder to understand (and our current discussion seems like a decent proof of that). And of course I'm not criticizing you, just trying to figure out what was your assumptions when you decide to go that way.

**Comment by davideas** [comment]
Hi, what you describe it's more likely the builder design pattern, which I would like to not adopt, because I think it's an extra layer of understanding. But you right, I can try to separate the 2 lines of execution (not easy), review the documentation and the javaDoc. Also, the method `expandItemsAtStartup()` has a similar concept: parents are expanded if items are present in the list, so if you add items later they remain collapsed, because not part of the initialization flow.

This complexity comes with the animations, scroll animations goes in conflict with item animators triggered by the `notifyXXX()` methods, the initialization in async way works, but it must better documented.

I'm going to open a couple of issue proposal for deprecation, refactoring, new methods, keep an eye on it.

**Comment by yamelkaya** [comment]
Ok. Thanks a lot.
