### ISSUE TITLE
Ask for small extension

### ISSUE THREAD

**Issue by kasterlod** [davideas/FlexibleAdapter#192]
Hello =]

It will be great if I could catch not only position but view too. I will be so much pleasure If you add smth like
boolean onItemClick(View v, int position); or
boolean onItemClick(int resourceId, int position);

or maybe there is possible to do that now with other methods?

greetings!

**Comment by davideas** [comment]
Hello, so you want the View in the Activity (or any class that implements the listener)?

Normally, you have the View in the ViewHolder, you just need to override the `onClick(View view)`.
Normally, the View is the Item View and should be managed only inside the ViewHolder for that Item. In the listener, you manage the item for your database and Adapter, that's why you have only the position.
