### ISSUE TITLE
updateDataSet with animate

### ISSUE THREAD

**Issue by kasterlod** [davideas/FlexibleAdapter#197]
Hello

tmpAdapter.updateDataSet(dataset, true) --> if animate parameter is true then updateDataSet function work only for the first time, when I called this function next times then only headers change its data but items none. The problem is only with animate true parameter.

greetings

**Comment by davideas** [comment]
@kasterlod, I can't reproduce it.
In which context you use it, with expandables or simple headers?

Try to enable logs before creating the Adapter (`mAdapter.enableLogs(true)`) and check what the adapter is doing. In general, the animation depends by some factors (all related each others):
- most important is the difference of the new list
- `stableIds` (should trigger a change for the items with same id),
- the flag to animate
- and of course the ItemAnimator linked to the RV **or** to the single ViewHolder as I just implemented.

However, if you see in the logs single notifications (or executing of notifications) then items should be animated with the item animator you set initially (for an insert/remove).
Did you play a bit with "Async Filter" and "Animations" use cases in the demoApp?

**Comment by kasterlod** [comment]
I remove headers from list --> sort list --> add new headers --> updateData
ids are indiviudal for all items
itemAnimator set as default
What does mean "the flag to animate"?

for the first time - headers and data updated:
D/FilterAsyncTask: doInBackground - started UPDATE
V/FlexibleAdapter: Animate changes! oldSize=14 newSize=14 limit=600
V/FlexibleAdapter: calculateRemovals total out=0
V/FlexibleAdapter: calculateAdditions total new=0
D/FilterAsyncTask: doInBackground - ended UPDATE

for the rest times - header updated but data no
D/FilterAsyncTask: doInBackground - started UPDATE
V/FlexibleAdapter: Animate changes! oldSize=14 newSize=14 limit=600
V/FlexibleAdapter: calculateRemovals total out=7
V/FlexibleAdapter: calculateAdditions total new=7
D/FilterAsyncTask: doInBackground - ended UPDATE

greetings

**Comment by davideas** [comment]
@kasterlod, the flag is the boolean for the method. I see that is `true`.
I understood the list is made of ISectionable + IHeader items. Some questions:
- Why you remove headers, and how you do it?
- What is the list of new items you pass? what contains?
From the 2nd refresh, I see that 7 items are removed and added, are they the headers?
- Also did you initialized the Adapter with stableIds?

**Comment by kasterlod** [comment]
I remove headers because i want to sort items and after that headers should change position too. Everytime I add headers I create new headers and adding to flexibleItems list (7 in that example). I think now to try not creating new headers each time but add created before.

**Comment by davideas** [comment]
I don't know what you want to achieve. Keep in mind that you should have an original source of items which you manipulate first, then use the Adapter to display items. Sorting that list, should not be done through the adapter, it just receives the new list with `updateDataSet(list, true)`.
As always, the new list should contains only the ISectionable items, that are the real data. Headers are just sections to organize the data.

That's why I asked, is the list different than the one currently displayed?

If the items are shuffled, they should be animated thanks to the single notifications. I can try to add this test case in the demo App, by tomorrow evening, but it's identical to the Filter use case,  They both use the same background "engine" to notify the modifications.

**Comment by davideas** [comment]
@kasterlod, are you still having problem with animation? could be related to the new issue #210?
