### ISSUE TITLE
New methods proposal

### ISSUE THREAD

**Issue by davideas** [davideas/FlexibleAdapter#201]
Add a your comment to propose a new method, explain the reason and the use case
where it might be useful. You can also use the +1 or -1 reaction to vote.

- [x] `void clear()`
- [x] `void clearAllBut(Integer... viewTypes)`
- [x] `boolean shouldNotifyParentOnClick()`

**Comment by davideas** [comment]
I propose `clear(Integer... viewTypesToKeep)` because often it is useful to remove all the items programmatically, and thanks to `viewTypesToKeep` parameter, some items won't be deleted.

Now we use `removeRange(int positionStart, int itemCount);` to remove all items or `removeItemsOfType(Integer... viewTypesToRemove)` opposite of the proposed method.

**Comment by davideas** [comment]
A new overload method for adding new item to the end of the list: `addItem(item)`.

**Comment by davideas** [comment]
Add a new method to trigger the parent notification change if it is expanded or collapsed.
The new method, named `shouldNotifyParentOnClick()` (or similar name), should be in `ExpandableViewHolder`.

**Comment by inorichi** [comment]
I think a `getItems()` could be useful sometimes. It could return a copy of the adapter list if you are concerned about it being modified.

My use case: I'm retrieving a list of items after a reorder (by a user drag). I'm using `onItemReleased` to notify the activity that the order has been altered, and I update my database after retrieving the current list and fixing the positions of my models. Currently I'm using a `for` from 0 to `getItemCount()` and calling `getItem(pos)` to create the list of items from the adapter.

The same usage could be applied to a `getSelectedItems()`.

Another possibility is a `setItems(List<T> items)`. I have a reactive database and when an item is modified, I receieve a new list and I have to replace all the items with a `clear()` and `addItems(0, list)`. I'm migrating my adapters from v4.2.0 (I've been using your great lib for a very long time) and I miss those.

They are not critical methods since you can workaround them, but it would be nice to have them available in my opinion.

Lastly, I would like to ask a bit of an offtopic question. I'm trying to find a clean way to keep my selections active after a rotation. My items stay alive after a rotation inside a presenter, and they are delivered again to the view after `onResume()`. As the selection state is stored in the adapter rather than the items (like the expanded state), I have to use the adapter `onRestoreInstanceState()`, but when this method is called the adapter is still empty and the selections are lost when `addItems` is called later. Any tip here?

**Comment by davideas** [comment]
@inorichi, thanks for the message.
Please open a new issue for the question about rotation and restoring selection.

`getItems()` might be added, since it might become useful in such situations as you described.

For `getSelectedItems()` I will need to cycle the selected positions and return a new list of items, I will evaluate if I will add it or not.

`setItems()` instead, is named `updateDataSet()` which is exactly what you need and it is much more advanced than a simple setItems.

**Comment by inorichi** [comment]
Oops, I was looking for a `*Items` method and totally overlooked the `updateDataSet` method (probably because it had a different meaning in 0.4.2). Sorry for not investigating enough.

For `getSelectedItems`, I'm doing that. When multiple items are going to be deleted in multi selection mode, I map the positions to the items, and call a method in my presenter to delete those objects passed as parameter.

About my issue, I'll try to give it some more thought before adding further noise here.

Thanks!

**Comment by davideas** [comment]
For removing selected items, you can call directly `removeAllSelectedItems()`, so you don't need to call remove one by one.
If you use the new `UndoHelper` you will need to pass the positions, too.
Having the undo enabled it gives you access to the `getDeletedItems()`.

When removing items from your original list / DB, you might have to do some additional operations, and you probably want to cast to your object `(CustomObj) mAdapter.getItem(position)` (if the generic was set with abstract type) when you cycle `getSelectedPositions()`.
Finally, if I create a cycle for getting items from positions, you then probably will cycle again the list.
So I won't create `getSelectedItems`.
