### ISSUE TITLE
How I can hide progressbar(onLoadMoreComplete)?

### ISSUE THREAD

**Issue by ulx** [davideas/FlexibleAdapter#202]
2) For questions / new feature / improvement
- How I can hide progressbar?
Metod  adapter.onLoadMoreComplete(null) does't work.
I have this image https://postimg.org/image/f5i5s9jtx/

**Comment by davideas** [comment]
@ulx, `onLoadMoreComplete(newItems)` should work, unless you have set null the progress item in the meantime.
Did you read the wiki page dedicated for the loading more and the javaDoc of this method?
Also, which version are you using? **b8** or **Snapshot** (check the latest modification in issue 39)?

It's supposed to be an automatic loading: if at start up you have not filled fully the screen with items, the the chain of methods for loading more will be called and progress item displayed if previously set, until you receive no more items by calling `onLoadMoreComplete(null)` inside the listener, it removes the item from the list. Check also the demo app, it works when no more load.

**Comment by ulx** [comment]
Sorry, I use **b8**

**Comment by davideas** [comment]
Probably is a second effect of the issue #184, can you try to use the Snapshot version?

**Comment by ulx** [comment]
OK, I will be try tomorrow

**Comment by ulx** [comment]
compile 'eu.davidea:flexible-adapter:5.0.0-SNAPSHOT'
It is not helped me.

**Comment by DarklyCoder** [comment]
I encountered the same problem!

**Comment by davideas** [comment]
Dears, would you try to share some code and logs? because in the demo app the `progressItem` is automatically removed from the list when no more load (new list empty or null). So, I would like to understand if there's a real problem or just a wrong configuration.

- If you are using method (A) with the item interfaces, the call to the endless listener is automatic;
- Try to follow the wiki page, the automatic loading is exactly what is done in the latest demo app (see also the java code in **rc1** branch for [FragmentEndlessScrolling](https://github.com/davideas/FlexibleAdapter/blob/rc1/flexible-adapter-app/src/main/java/eu/davidea/samples/flexibleadapter/fragments/FragmentEndlessScrolling.java)).

**Comment by ulx** [comment]
@davideas , you right 
FragmentEndlessScrolling is work normal.
I use ProgressItem.java from sample. Is it my wrong?

**Comment by davideas** [comment]
@ulx, allright, make more tests then decide if you can close this issue.

I don't how you mean the loading more, but for me, in the implementation of this listener there should be only the call for a Rest(?) API (for instance), for a remote call with a gateway service class. When the remote call receives a response, in another user defined method, then, in this third method, we update the local database and the user interface by notifying the adapter by calling `Adapter.onLoadMoreComplete(newItems)`.

**Comment by ulx** [comment]
Sorry, It was my wrong.

**Comment by davideas** [comment]
Please be aware that, Endless Scrolling is going to be changed very soon. In order to support the new features and a better logic, the behaviors and callbacks methods will be refactored.

Please check issue #233 for the latest developments.
