### ISSUE TITLE
Problem with item content change animation

### ISSUE THREAD

**Issue by bejibx** [davideas/FlexibleAdapter#210]
The question is about version 5.0.0-b7.

Hi! I'm trying to animate my adapter from one list to another using `FlexibleAdapter#updateDataSet(List, boolean)`. Sometimes new list has same elements order, but some elments content may change. If I override `Object#equals(Object)` in my items so that full item content is taking into account, changed items animated using remove-add animates. Instead I want to just update their content. I was tried to achieve this using `FlexibleAdapter#setNotifyChangeOfUnfilteredItems(boolean)` and override `Object#equals(Object)` to compare only ids. After that items won't update at all after initial update. 
I noticed strange logic in method ``FlexibleAdapter#applyAndAnimateRemovals(List, List)`:

``` java
final T item = from.get(i);
if (!newItems.contains(item) && (!isHeader(item) || (isHeader(item) && headersShown))) {
    //...
} else if (mNotifyChangeOfUnfilteredItems) {
    from.set(i, item); // here element at position i is updated with itself
    notifyItemChanged(i, mNotifyChangeOfUnfilteredItems);
    if (DEBUG) Log.v(TAG, "animateRemovals   keep position=" + i + " item=" + item);
}
```

Instead of updating item at index i with new item, old item gets assigned at self position, so in fact there is no update there. I think it should be:

``` java
from.set(i, newItems.get(i));
```

**Comment by davideas** [comment]
@bejibx, I think you are right, thank you to have spotted it!
Initially the animation was only for the filter, later on, I decided to reuse it for the update too, that's why of this bug.

I will try to keep the same performance by moving that notification in the `applyAndAnimateAdditions()` method, because in this method the `newItems.get(i);` comes for free (the cost to call `get(position)` is high in big list).

A change that you will have to do:
With **beta8**, that part of code is changed: every calculation you see is done in background and also it makes use of `Set`, but that assignment is still there and I 'm going to fix it in the **Snapshot** which now contains the **beta8** too + new fixes already. So, you will have to upgrade your code and perhaps make some changes here and there.

**Comment by bejibx** [comment]
@davideas ok, thank you!

Btw, don't you think about using [```DiffUtil```](https://developer.android.com/reference/android/support/v7/util/DiffUtil.html) from support library which already can compute difference between two lists in background?

**Comment by bejibx** [comment]
@davideas oh, and could you please ping me when this is done, so I can switch to snapshot and test it?

**Comment by davideas** [comment]
@bejibx, I made several tests and for me, the update should work with the new item, but the modification must be `from.set(i, newItems.get(newItems.indexOf(item)));` otherwise indexes are out of bounds when the list of newItems is smaller than existing list. Doing this it becomes slower if you have to rebind all existing the items.
For the moment, to compare if really 2 items are different the `equals()` and `hashCode()` of the item play an important role. Based on that, the `HashSet` returns true or false when `contains()` is invoked: if false than it's removed and added again in `applyAndAnimateAdditions()` but here it's much faster; if true the boolean `notifyChangeOfUnfilteredItems` must be true as well.

To not rebind all items and not having the removal + addition, I still need to retrieve the index from the List of the new items to eventually give both items to the user, so he can compare the others fields, (same concept of DiffUtil when items have equals returning true).
To do this I need a new method in `IFlexible`. To analyse better.

**DiffUtil**
I finally added the `DiffUtil` as suggested not only from you. Now, the Adapter has 2 solutions: _my calculations_ or _DiffUtil_. What will you choose? well, for me that I made the tests, DiffUtil has a problem with medium and big list, I don't know if my implementation is correct, but studying others blogs, I think yes and the time took by this new Android class is extremely slow!
You can make some tests.

**How does it work?**
I've added new methods to activate the type of calculation and to set the custom callback, if no custom callback is set, the default is used, it will rebind all items that `equals` returns true.
I also added the method `getTime()` that returns the time took to calculate the different solutions.
The demoApp has been modified for the Async Filter, so you can activate from the menu the option to enable/disable the usage of `DiffUtil`.

In my calculation the critical method is `applyAndAnimateMovedItems` that remains very slow. Keeping this disabled the whole process remains extremely fast even the double of DiffUtil. However, if have a different algorithm for this method, you can suggest.

**Comment by davideas** [comment]
@bejibx, I've improved a lot the update notifications by using the _hash_ without calling `indexOf()`.
In `applyAndAnimateRemovals()`, the code seems complex using Set+Map and 1 more for-cycle, but it's super fast.

I have committed this new change, but not created the new Snapshot yet. I wait you to test the old code in your app, so you can compare the DiffUtil solution with my old solution.
But, if you update your clone project, you can check my new solution in the demoApp in the emulator: the update notifications are just few _milliseconds_ instead of _seconds_ as before (i'm talking about 10.000 items in the AsyncFilter example).

At this point we probably need a new method that creates a custom Payload so the library can pass it for the binding, now only `Payload.CHANGE` is created and passed.

**Comment by bejibx** [comment]
Hi again! Firstly, about ```DiffUtil```. Actually, my question was just a question, not really a feature-request or something. I was never tested it's performance, just wanted to know your opinion about it.

Now about content changes. It seems it worked as expected now. The fact you need to override ```Object#hashCode()``` the right way (use only id as hash in my case) is kind of puzzling though, you should have an idea about how adapter internally checks object equality. 

I agree about new method for custom payload. ```DiffUtil.Callback``` have two methods for this - ```#areContentsTheSame(int, int)``` and ```#getChangePayload(int, int)```. Maybe it is better to use only ```#getChangePayload(int, int)```-analog with ```null``` result indicating that items are completely same.

**Comment by davideas** [comment]
@bejibx, well, beside your question, it was more to understand how this new class works since also others asked, and I found out that, more differences there are slower it is, (this is in their doc too). But, because I wanted to keep the high performance for the filter, I included it to compare it with my solution: I found out that `DiffUtil` is very slow and I ended up to optimized my solution and resolved this bug as well.

- About the `hashCode()` there's a point in the refactoring proposal (issue 200), to add it in the `IFilterable` item interface or even in `IFlexible`, I think I will do it. So everybody has to implement it, if he will use Update/Filter/Expandables (when collapsing all).

- About the payload, I completely agree to check the `null` value instead of invoking `areContentTheSame()`, using both functions it makes no sense.
The new method should be always for `IFlexible` but without positions because the `get()` is already done by the Adapter, it will be something like ` Payload getChangePayload(newItem instance)` (oldItem is `this`) OR `Payload areContentTheSame(newItem)`.
The adapter will call `Object payload = oldItem.areContentTheSame(newItem);` the user will return a non-null payload if a mismatch occurs, otherwise null, so I will not invoke the notification.

- Another aspect, for the Update use case, is the flag `notifyChangeOfUnfilteredItems`. It has sense only in Filter use case. Update use case should now delegates to this new function if updating the item or not, so I will review this check too.
