### ISSUE TITLE
[Question] The next steps of your development

### ISSUE THREAD

**Issue by djuelg** [davideas/FlexibleAdapter#224]
Hey there!

I have two basic questions about your schedule:

- Do you plan to release another beta version or 5.0.0 as next step?
- Can you estimate how long the development of 5.0.0 will go on until it's release?

Greets,
djuelg

**Comment by davideas** [comment]
@djuelg, thanks for the nice question.

I plan to release a couple of Release Candidates (**rc1** and **rc2**): I will have to deprecate some functions and probably separate the library from the extensions, maybe adding a lighter version of the Adapter with only the basic functionalities.

I have to publish the demoApp on Play Store as well...

About the timing, well, net less of 2-4 months.

**Comment by djuelg** [comment]
Ok, thanks for your answer and this great project.

Happy coding! :)

**Comment by davideas** [comment]
I have now a clearer plan for the next releases. However, I don't know if I will be able to maintain the dates I've set, but I will try according to the free time.

Here, the main points of **rc1** milestone:
- [ ] I'm working on the new big feature of **Scrollable Headers** and **Footers**. Since this feature brings lot of new code, it must be closed as soon as possible.
- [ ] I need to improve the **EndlessScrolling / LoadingMore**: how it is now, it is not good and with the new concept of footers the _progressItem_ could become a footer item.
- [ ] I need to fix 2 small but annoying bugs in **scrolling animations**.
- [ ] I have to **refactor / deprecate** many functions, however, they will be removed in the final release. So this also must be done asap too.
- [ ] I can simplify a lot the **configuration** for the **sticky header container**, doing so the we can remove the layout from the our xmls.
- [ ] Need to add the possibility to add **elevation** to the _header item_ and to the _sticky header container_.

For **rc2** milestone:
- [ ] I need to evaluate the creation of a separate library for the extensions.
- [ ] Extension to support **Realm** and **Firebase** adapters.
- [ ] More example for the demoApp.
- [ ] Finish the Wiki pages.
- [ ] Some bug fixes that come from **rc1** pre-release.

For **final** release:
- [ ] Some other code adjustment that will appear clearer with time.
- [ ] Delete of all deprecated functions.
- [ ] Some bug fixes that come from **rc2** pre-release.
- [ ] Review of the demoApp and the documentation.
- [ ] Publishing to PlayStore.

**Comment by davideas** [comment]
To support of Realm, Firebase and Cursor I need to review the way how the items are stored, making another level of abstraction, so I will focus on them in the **rc3**, while now I will focus to close the rc2 with the planned work.
I also close this issue, to create a new one (#361) with more detailed points.
