### ISSUE TITLE
[Question] How to use 2 adapters in single Activity? How to handle itemOnClick for both adapters? 

### ISSUE THREAD

**Issue by khalid-mahmood** [davideas/FlexibleAdapter#225]
[Question] I am using 2 Adapters in single activity, how i can handle the itemOnClickListner separately for each adapter ?

**Comment by davideas** [comment]
@khalid-mahmood, you actually can use multiple Adapters for different RecyclerVews, indeed.
To handle the click listeners, you need to distinguish in the same implementation of `onItemClick()` which RV / Adapter has triggered the event: basically which list the position is referring to.

Now, the only thing that comes in mind quick that sure works, is to override the `onClick()` of the `FlexibleViewHolder` and save somewhere the type of the View or the Adapter that generated the event, then you can call `super()`. Then in the `onItemClick()` you check which is the adapter to call `getItem()`.

Another cleaner solution, is to provide you also the View, but I prefer to Not modify the method signature of the Listener in the library, need more justification since it has very heavy impact to everybody.

**Comment by davideas** [comment]
@khalid-mahmood, another clean solution is to use Fragments: each fragment includes the own Adapter and implements the proper listener.

**Comment by khalid-mahmood** [comment]
static field used to identify the adapter, crazy hack
already using fragment. in fragment using two adapters.
 @davideas can you make simple like. pass adapter too with item position in onItemClickListner(int position).
Thanx for help.. Good Work.

**Comment by davideas** [comment]
@khalid-mahmood, I see, but I can't modify that method as explained.

Another solution (best I think) is the following:
Instead of the Fragment implementation you create 2 custom fields of type `OnItemClickListener`, so you can implement the method and assign it to the right adapter. That listener will be called only by that Adapter.

``` java
private FlexibleAdapter.OnItemClickListener clickListenerAdapter1 = 
		new FlexibleAdapter.OnItemClickListener() {
	@Override
	public boolean onItemClick(int position) {
		//...
		return false;
	}
};

mAdapter1.initializeListeners(clickListenerAdapter1);
```
Same for the 2nd Adapter.

**Comment by khalid-mahmood** [comment]
@davideas  Thanks. This Works Like Charm.. 
but same issue with empty list.  any more suggestion?

**Comment by khalid-mahmood** [comment]
adapter.initializeListeners(onUpdateListner1);
 used same for Update Listener. working fine.
Thank you so much for help @davideas

**Comment by davideas** [comment]
@khalid-mahmood, yeah, you got it.
For the next releases I'm going to deprecate/rename that method in favour or `addListener()`. What do you think?

**Comment by khalid-mahmood** [comment]
addListener() good for understanding.. consider it.
