### ISSUE TITLE
Question: Height of Header takes entire section during scroll

### ISSUE THREAD

**Issue by ahmedkhan23** [davideas/FlexibleAdapter#226]
I can't figure out what I am doing wrong but my Header as soon it starts to stick, it's height takes up the height of the entire section. I am hoping this is a quick answer for anyone reading. If not I can add all relevant details.

**Comment by davideas** [comment]
@ahmedkhan23, you probably have a height param not compatible in the layout for header item, that information is copied to the header container which then .
Please check the `ensureHeaderParent()` method which is responsible for that: [StickyHeaderHelper.java#L217](https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/helpers/StickyHeaderHelper.java#L217)

**Comment by ahmedkhan23** [comment]
Thanks so much for the quick reply.
What I gather is that the height of header view layout cannot be set to "wrap_content", is this correct ?

**Comment by davideas** [comment]
@ahmedkhan23, no, actually you can set `wrap_content`. So what do you have as layout?

**Comment by ahmedkhan23** [comment]
@davideas , here it is 
https://github.com/ahmedkhan23/android-samples/blob/master/FlexibleAdapterDemo/app/src/main/res/layout/header_cell.xml

if you look at the height of the root RelativeLayout, you will see that if you set it to a hard value like 45 dp, it will work, but if you set it to wrap content, as you scroll up, when the header sticks, it takes the value of the entire section.

Also @davideas  if you can just pull and run the project it would be great. It's my first time using the library. I followed the wiki as best I can but do feel I am missing some things. It's a barebones implementation.

What I notice is that whenever the activity is resumed again, I get duplicated headers -> I don't know if you can help me resolve this issue.

Thanks a lot.

**Comment by davideas** [comment]
@ahmedkhan23, I got your issues solved! But for this time it passes because both of your issue were extremely easy to resolve. Next time please review your code before opening an issue, because:

1. Height problem is caused by the bad layout implementation of the `RelativeLayout`: Delete `android:layout_alignParentBottom="true"`, but you should also clean this layout by others useless lines (maybe you are just testing, but as you see if others parts are not correct you might get troubles elsewhere, and this was the case).
2. Where have you read that the objects creation should lay in `onResume()` of the Activity?!? Delete `onResume()` function for now because currently you don't need, so you put everything in the `onCreate()` function. And please read the Android Activity life cycle for a knowledge refresh.

For the rest of the demo, as initial try, it looks fine. Check better each method / functionality before using it so you might have a better idea of what it does: Read the javaDoc of the method and use the Wiki as general reference.

Another little thing. The logs should be enabled before you initialize the Adapter, that's why the method is _static_. The editor shows a warning "Static member 'TestAdapter.enableLogs(boolean)' accessed via instance reference". It means you should do: `FlexibleAdapter.enableLogs(true);`

**Comment by ahmedkhan23** [comment]
@davideas -> Thanks a lot for your input. I made the changes and things look fine. After playing around with 3 or 4 other libraries I think my head was just spinning. Thanks for giving me the pass. I needed it.
