### ISSUE TITLE
Do not invoke EndlessScrollListener.onLoadMore() if new items < pageSize

### ISSUE THREAD

**Issue by lijunguan** [davideas/FlexibleAdapter#233]
First,please forgive my poor English.

I expect to have a method can set "page size",and  won't invoke ```EndlessScrollListener.onLoadMore() ``` if item count less than(<=) page size.
Actual,when i first load data from Services API and amount of data less than page size, will invoke ```EndlessScrollListener.onLoadMore()``` and tigger Services API to needlessly load more data . 

in addition,do you plan to release new version to add new feature in rc1 branch,such as ```DiffUtils```.  
This library with perfect doc and detailed code note, I benefit a lot from it.Thank you very much for your contribution.

**Comment by davideas** [comment]
@lijunguan, the pagination is an improvement(?) that can be added.

However, here it's slightly different: once you know that no more items will be retrieved (you should know this information), you can call the `onLoadMoreComplete(newItems, delay=-1)` to automatically resetting the internal `progressItem` reference to null, in this case the item remains visible and a `notifyItemChange` to this item is invoked: you check that the `Payload.NO_MORE_LOAD` is sent and display a text message instead of the progress icon (design this item layout properly).

If you have a `SwipeRefreshLayout` and the user scrolls it down, it won't trigger the loading more. If the user doesn't refresh you should have the item with the text message displayed.

I did not used this functionality in real, and I know that, I should review a bit this mechanism by improving the example and maybe I can add a function `isEndlessEnabled()` that returns `false` if the internal reference is null. I can even automatically reset the progressItem when no more load. There are several ways to achieve this, and I should try them as well for a real simple use case.

Regarding **DiffUtils**, you can actually try it with the current Snapshot version, but be aware that probably I will remove in the final version, there's issue #210 where you can read my analysis.
Moreover, the demo app in rc1 branch has an option that you can enable/disable to see the differences at runtime, while filtering or updating, check the Async Filter example.

**Comment by lijunguan** [comment]
i think the paging function is useful,when item  Less than one page should not be invoke onLoadMore() listener.  Yes, I  know no more items , call onLoadMoreComplete(newItems, delay=-1) and  display a "no more data" message instead of the progress icon.   but  show a Item and a "ProgressItem ("no more data " promt item)" in Screen  is very strange. 

Another question,why  ```OnUpdateListener``` should  be Called at startup?   Because, i initialized adapter with a empty list, and load data in other thread ,then call updateDataSet() in main threa. I will show a loadingView at first initialized ,  until data load complete and  invoke  ```onUpdateEmptyView(int size) ``` listener to handling emptyView show or hide and hide loadingView.  
```java
 @Override
    public void onUpdateEmptyView(int size) {
        Timber.d("onUpdateEmptyView size = %d", size);
        if (size > 0) {
            mFastScroller.setVisibility(View.VISIBLE);
            mEmptyView.setVisibility(View.GONE);
        } else {
            showEmptyUi();
        }
        mLoadingView.setVisibility(View.GONE); //if this listener called at startup, need delete this line ,
    }
```
the result is not what I expected, so l look source code and find OnUpdateListener  called at startup, I don't know why.

**Comment by davideas** [comment]
@lijunguan, I agree with you, yesterday I got some time to experiment more this feature. I now commit what I have in **headers_footers** branch, be aware that code is not finished (I will put on rc1 branch and publish a snapshot when eventually works). But just to give you an idea on what I'm working on. There will be a breaking refactoring for `EndlessScrollListener` I will also provide `lastPosition` and `currentPage`.

Then, there's another feature for when we reach the limit instead, that I called `endlessTargetCount`. That and `pageSize` can be both activated or not, so we will have 3 features:
- new items less than pageSize previously set
- total item count reached the target previously set
- none of the above is set, the Adapter will always attempt to load more.

I will answer you later for the emptyView.

**Comment by davideas** [comment]
@lijunguan, about the emptyView callback, considering that **all users** have that particular statement `if-else`. If the call is not triggered at startup, the empty view will be visible when items are present too, then it will be a bug for that.

It's because you have the loading view too in the code dedicated for the empty view.
I think you start with loading view as `visibility=VISIBLE`. So you evaluate 2 solutions>
- Check if adapter has been attached to RV. It should be `null` in that moment because at startup you still didn't set the adapter to it. This should happen only during the initialization phase.
- Change the visibility to `GONE` at the end of loading process.

**Comment by lijunguan** [comment]
I've already seen your new branch,New feature is highly useful to me.   I have a question,  why not consider add limit for onLoadMore()?   eg:
```java
protected void onLoadMore(int position) {
		.....  
                //if itemCount less than pageSize don't call EndlessScrollListener
		if (position < threshold ||  getItemCount(false) < mEndlessPageSize  || position == getGlobalPositionOf(mProgressItem)) {
			return;
		} 
              ......
	}
``` 
if not ,Show the progressItem  may not be desired.  example : just show one item with progressItem ,even if I  setEndlessPageSize(10).   In addition, ```getEndlessCurrentPage()``` may not work properly.

>Consider adding new feature to support retry if loadMore error ? Of course I can implement it by addScrollableFooter() now.

**Comment by davideas** [comment]
@lijunguan, very good you like the latest additions. Please update again, because yesterday evening I've already committed changes with the limits checks for items less than `pageSize` and total items bigger then `targetCount` which will automatically disable the endless scroll forever.

You can avoid to display the message, just don't provide any delay while calling, but if you want to give a retry you can add a button in the progressItem and when notified for the change you hide the progress and show the button. Or you can implement the `SwipeRefreshLayout` and simply display a message for few seconds or more (as I did in the demoApp).

If you want to make the loading more completely manual, don't implement the listener at all, just add the progressItem it should not be deleted when noMoreLoad, but stick there with a button ready to be pressed again. In theory this should work...
I will make few examples to see the different use cases.

Then, I will try to add support for endless top scrolling, not easy to do.

A question that maybe you can answer regarding the Scrollable Headers and Footers, in the new code, the empty view is called with the size without those special items, it means if no main items are present then empty view is visible but headers and footers are visible too.
The question is, _what would you expect to provide, the number of items included headers and footers or only the number of the main items?_
