### ISSUE TITLE
Sticky header noticeably blinks (fades in) on its first show

### ISSUE THREAD

**Issue by ayzenquwe** [davideas/FlexibleAdapter#239]
Happens only in the last SNAPSHOT version, in 5.0.0-20161022.133456-44 everything is okay.

I think this happens when sticky_header_layout is being shown for the first time.

**Comment by davideas** [comment]
@ayzenquwe, thanks to have report it. I think I have reproduced it too, however I am currently reviewing the `StickyHeadersHelper` to introduce a new way to configure the layout, elevation with shadow and fixing small issues like that. In my local version that doesn't occur anymore.

If instead you talk about the _fade-in_ and _fade-out_ animations, those are wanted.

**Comment by ayzenquwe** [comment]
Okay, thanks for information. I'll stick to 5.0.0-20161022.133456-44 for now. Looking forward to the new snapshot version. :)

**Comment by davideas** [comment]
The next Snapshot will have more a face for **rc1** rather than small improvements and fixes.
Lot of changes, some breaking changes, but another good news is that I will prepare a migration guide from previous versions.

All new changes are already visible in the [milestones page](https://github.com/davideas/FlexibleAdapter/milestones)

**Comment by davideas** [comment]
@ayzenquwe, for your information, a new snapshot has been released.

**Comment by ayzenquwe** [comment]
Thanks! I'll check it out later.
