### ISSUE TITLE
Use Sticky Headers in FragmentPagerAdapter

### ISSUE THREAD

**Issue by leodeleon22** [davideas/FlexibleAdapter#242]
Hey @davideas 

I want to use sticky headers in two equal fragments that are in a viewpager but when I set both fragments only the first one stays sticky, the header dissapears when I scroll the second one. I guess it has something to do with the recycler view.

Any ideas on what I could try to achive this behavior?

**Comment by davideas** [comment]
@leodeleon22, yes I know that behavior, please read issue #179. I think you should temporary use the Snapshot version.

But, as I anticipated in you previous issue, in the next pre-release, it will be even more simple. I'm currently working on it. A migration guide will be ready for the next snapshot.

Anyway, be careful adopting this version because you will compile with my latest publication without notifications.

**Comment by wankey** [comment]
I have use the Snapshot version , and call method setStickyHeaderContainer ,bug stickyHeader doesn't work in the second pager.

`FlexibleAdapter adapter = new FlexibleAdapter(this);
		adapter.setStickyHeaderContainer(( ViewGroup ) LayoutInflater.from(mActivity).inflate(R.layout.sticky_header_layout, null, false));
		adapter.setUnlinkAllItemsOnRemoveHeaders(true)
				.setDisplayHeadersAtStartUp(true)
				.enableStickyHeaders()
				.showAllHeaders();`

**Comment by davideas** [comment]
@wankey, if you inflate the ViewGroup it should have a parent already attached to the hierarchy otherwise the layout is not rendered.
I found 3 different ways to achieve the sticky header with ViewPager:

- If you have the ViewGroup already in the layout as in my examples, you can do:
``` java
//Sticky Headers
mAdapter.setStickyHeaderContainer((ViewGroup) getView().
				findViewById(R.id.sticky_header_container))
		.setDisplayHeadersAtStartUp(true)
		.enableStickyHeaders();
```
You can also check in rc1 branch, the new sample FragmentViewPager.

- You can extend the Adapter and override:
``` java
@Override
public ViewGroup getStickyHeaderContainer() {
	FrameLayout frameLayout = new FrameLayout(mRecyclerView.getContext());
	frameLayout.setLayoutParams(new ViewGroup.LayoutParams(
			ViewGroup.LayoutParams.WRAP_CONTENT, //or MATCH_PARENT
			ViewGroup.LayoutParams.WRAP_CONTENT));
	((ViewGroup) mRecyclerView.getParent()).addView(frameLayout);
	return (ViewGroup) mInflater.inflate(R.layout.sticky_header_layout, frameLayout);
}
```

- With the official rc1 pre-releaes all this is not necessary anymore, you can already read the new Wiki page [migrations](../wiki/Migrations), to be ready for when i will release it.

**Comment by wankey** [comment]
@davideas, thank you for your response. I have used the first way to solve this problem.
