### ISSUE TITLE
Topmost header turns white when items added above it

### ISSUE THREAD

**Issue by lemonboston** [davideas/FlexibleAdapter#244]
Using `eu.davidea:flexible-adapter:5.0.0-b8`.

Sticky headers work nice for us, but I encountered an issue:
When the RecyclerView is fully scrollled to top and new items are added into the beginning of the list with `flexibleAdapter.addItems(0, newItems);`, then the top header turns white. From that position when scrolling down, the stikcy header is not displayed. If scrolling up from that position, the header appears back abruptly. 
See screenshots below. Any tip why this happens and how to fix it?

Original state, scrolled to top:
![01_before_insert](https://cloud.githubusercontent.com/assets/1077972/20837112/dab92f76-b8a2-11e6-9e62-de9788bfc4b2.png)

After items are added at position 0:
![02_after_insert](https://cloud.githubusercontent.com/assets/1077972/20837114/daba9442-b8a2-11e6-85fc-9e10d3a4ee3e.png)

When starting to scroll down from there:
![03_scroll_down_1](https://cloud.githubusercontent.com/assets/1077972/20837115/dabaaab8-b8a2-11e6-8767-90a5c381495f.png)

Scroll down a bit more:
![03_scroll_down_2](https://cloud.githubusercontent.com/assets/1077972/20837116/dabb84c4-b8a2-11e6-801b-7062b5ea4861.png)

When starting to scroll up from state 2:
![03_scroll_up_1](https://cloud.githubusercontent.com/assets/1077972/20837113/dab96748-b8a2-11e6-9aa9-e74ccfd9cc00.png)

Scolling up a little more:
![03_scroll_up_2](https://cloud.githubusercontent.com/assets/1077972/20837117/dabc74a6-b8a2-11e6-8b55-33b39ca40c81.png)

**Comment by lemonboston** [comment]
From the logs:
```
12-02 17:41:07.604 W/View: requestLayout() improperly called by android.widget.FrameLayout{abd0ad6 V.E...... ......ID 0,0-1080,95} during layout: running second layout pass
```
The sticky_header_container framelayout gets zero height measured.

**Comment by davideas** [comment]
@lemonboston, I see that warning too only if header is already translated scrolling a bit, but is not triggered by me, and I don't see any glitch because of that, so I exclude it.
But, please tell me if in the demoApp, class `FragmentHeadersSections` line 116, doing so I can reproduce your use case:

``` java
//Commeting these lines
//mAdapter.addUserLearnedSelection(savedInstanceState == null);
//mAdapter.showLayoutInfo(savedInstanceState == null);

mRecyclerView.postDelayed(new Runnable() {
	@Override
	public void run() {
		IHeader newHeader = DatabaseService.newHeader(555);
		SimpleItem iSectionable = DatabaseService.newSimpleItem(999, newHeader);
		mAdapter.addItem(0, iSectionable);
	}
}, 5000L);
```

Doing that in beta8 I don't see any hiding nor movements of the header: the 2 items are added (but not visible) and the sticky header is swapping correctly. How can I reproduce it?

**Comment by davideas** [comment]
@lemonboston, I've tried your app. The problem comes only with the scroll, the second layout occurs and it removes the content of the layout. But currently, user has no choice if he scrolls up or down: the app triggers a call anyway to load on the top in both situation. It's strange.
I think the problem of header that disappears, it's when you scroll down (it's opposite how you say), so you are not interested to load items a position 0.
When you want to load more on top, you can insert a progress item at position 0 and scroll to it (`addItemWithDelay` use a delay 0, the call is in post), when data comes you put the new items and finally you remove it.
If you decide not, with next release I will put a minor fix to avoid the swapping if the header is the same item at first layout position.

I've completely reworked the endless scroll at bottom, maybe I will try to add a loading more at top, but it will be available with next snapshot or rc1.

**Comment by lemonboston** [comment]
@davideas First of all, thanks a lot for looking into this!

What we would like to do with this list is that after loading the requested set of items (page) on screen startup, load the previous page as well automatically and add to the top, so user can start scrolling upwards if they liked to. It's currently disabled, but you can enable it in our app by uncommenting this line: [link](https://github.com/schedjoules/android-event-discovery-sdk/blob/f143950f9decad808a5e493a0a217bc3647ea17f/eventdiscovery-sdk/src/main/java/com/schedjoules/eventdiscovery/eventlist/itemsprovider/EventListItemsProviderImpl.java#L317-L317)
So in this case it's independent from scrolling, we would like to add those items without any user interaction.
Using a progress item on top and bottom is already in our backlog to implement, not sure if that would solve this though. Maybe I will try.

Looking at your example to reproduce it in your demo app I realized that the Header is not added to the list, which I also found in bold in the wiki afterwards, I totally missed it. It says: _"..The Header item doesn't have to be added directly to the list.."_. Does it mean that it must not be added?
They are currently added in our app, I tried to remove them now but then they are not shown - tried to play with setDisplayHeadersAtStartUp() enableStickyHeaders() showAllHeaders(), maybe I just miss some order. If you say it's better not to add them, I will try to update after comparing with your demo.

Maybe I will also try to build from your branch with the partially fix commit to see if that simply fixes our issue.

**Comment by davideas** [comment]
@lemonboston, pay attention that the branch headers_footers, has a lot of new and deprecated code (check milestone rc1), I worked a lot last week on it: it will be the code for rc1. So you can use it, it works quite well, it is well documented already with javaDocs only.
Just pay a lot of attention at the layout used in the demo `fragment_recycler_view.xml`, because I reduced the configuration in it, but you will still need the FrameLayout wrapping the RV.

So, you only need these 2 settings: `setDisplayHeadersAtStartUp() + setStickyHeaders()`.
because your main items are the feeds, and the dates are just header items used to regroup logically your main items. That's why headers are handled by the adapter in this use case.

Different use case is done with the expandables, where the expandable should be considered as main item, even if it can behave like a header too.

**Comment by lemonboston** [comment]
Your fix works in our app! Hallelujah :)

So I used your `headers_footer` branch last commit with jitpack.io:
`compile 'com.github.davideas:FlexibleAdapter:0320868e9319c87926e645cd620f93ab12b9ba3b'`
And the topmost sticky header item doesn't disappear now when items are added on top of it.
I know it's a work in progress branch, we will switch to your next release version when it's available. Do you maybe see any particular risk in using this version, though?
Thanks.

**Comment by lemonboston** [comment]
Ok, thanks for the info! It looks good after the update on our side, so we will use that revision for now.
(FrameLayout wrapping is already there, and I changed enableStickyHeaders() to setStickyHeaders())

**Comment by davideas** [comment]
Very good. But doesn't turns again white if the scrolling doesn't scroll out the full header item?

The only risk is that, it is not so much documented: you need to clean your code from the deprecated code, you have the new scrollable headers and footers, new endless scroll, header elevation, and a lot of optimizations.

**Comment by lemonboston** [comment]
> But doesn't turns again white if the scrolling doesn't scroll out the full header item?

I am not sure what you mean, but it works correctly scrolling in both direction after 2nd load finished (or before). You can check it out from this branch: 
[bugs/3-top-header-glitch](https://github.com/schedjoules/android-event-discovery-sdk/tree/bugs/3-top-header-glitch)

Thank for the notes on the risks, it sounds good then.
(We don't use the loading/endless scroll stuff from the library at the moment, maybe will check back to it later. And just added a note to backlog about trying the header elevation.)
