### ISSUE TITLE
Best way to create ExpandableList with multiple View types. 

### ISSUE THREAD

**Issue by aboikanych** [davideas/FlexibleAdapter#246]
What the best way to create ExpandableList that have 2 types of view. If group item doesn't have any child this item will be the same as child view. If group view have child, we provide title for group view and this view need to be expandable.

```
        {
          "description": "Desc1",
          "expandable": true,
          "title": "Title1"
        },
        {
          "description": "Desc2",
          "expandable": false,
          "title": ""
        }
        {
          "description": "Desc3",
          "expandable": false,
          "title": "Functional testing:"
        }
```

![image](https://cloud.githubusercontent.com/assets/23631516/20970344/d104ce9e-bc95-11e6-9702-fb1d31ac6466.png)

**Comment by davideas** [comment]
Hi @aboikanych, question, can the simple item become an expandable due to some events or born already in that view and it remains?

In the second case, I would suggest to create 1 item with same view _id_ for "sub-item" and "normal item" at the same level of the others expandable but with no parent, when instead you have the expandable that view functions also as sub-item but it lays in the child list of the expandable.

If it instead it switches at runtime, you can call the `update(global position of normal, expandable item)`. It will trigger a `notifyItemChange`, I think it should work... If not you can remove the old and add the new one at the same position.

Always distinguish the model items from the adapter items.

**Comment by aboikanych** [comment]
I have already list of items with all data before creating the adapter and all data is static. I will create 1 item for both _id_ and 1 for expandable item. After that I need create list of this objects and simply set it to adapter?

**Comment by davideas** [comment]
@aboikanych, to the adapter list, you add expandable items and the normal item, not the subItems that are already inside the expandable:

- Normal item1 viewId=A _(add this item)_
- Expandable item1 viewId=B _(add this item expanded=false by default)_
  - SubItem1 viewId=A
  - SubItem2 viewId=A
- Normal item2 viewId=A _(add this item)_
