### ISSUE TITLE
How to automatically scroll to the specified header item?

### ISSUE THREAD

**Issue by shymmq** [davideas/FlexibleAdapter#256]
If I understand correctly, getGlobalPositionOf() only searches in the list of items provided in the constructor. How to get global position of a header(based on it's instance) so it can be used in recyclerView.scrollToPosition() ?

edit: i have already correctly implemented equals() nad hashCode() methods

**Comment by davideas** [comment]
@shymmq, `getGlobalPositionOf` returns the position of any item at any time, also for Headers if they are visible! So you can scrollTo using that method.

Good that you implement `equals` method, because List makes use of it.

**Comment by shymmq** [comment]
Hmm, for some reason getGlobalPositionOf() always returns 0. Can you quickly check the following code?
```java
//in onCreateView:
RecyclerView recyclerView = (RecyclerView) root.findViewById(R.id.fragment_timetable_recycler);
Collections.sort(schoolWeeks);
for (SchoolWeek schoolWeek : schoolWeeks) addSchoolWeek(schoolWeek); //listElement items are being added here, with respective header items.
final FlexibleAdapter<IFlexible> adapter = new FlexibleAdapter<>(listElements);
adapter.setDisplayHeadersAtStartUp(true);
LinearLayoutManager layoutManager = new LinearLayoutManager(getContext());
recyclerView.setLayoutManager(layoutManager);
recyclerView.setAdapter(adapter);
int sectionIndex = adapter.getGlobalPositionOf(todayHeader);
Log.d(TAG, "onCreateView: Scrolling to position " + sectionIndex);
layoutManager.scrollToPositionWithOffset(sectionIndex, 0);
```
Using debugger i checked that `todayHeader` is in fact being correctly set in `addSchoolWeek()`

This is equals() from my header item class:
```java
@Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        LessonHeaderItem that = (LessonHeaderItem) o;

        return date.equals(that.date);
    }
```

**Comment by shymmq** [comment]
Does the `getGlobalPositionOf` use `equals(),` or `==` to compare the items?

**Comment by davideas** [comment]
I said at any time, but it is not really true at startup, sorry:
`scrollTo` is strictly linked to the layout manager, as Android team says, layout items might not match with adapter items due to layout operations. So we should also invoke `scrollTo` after the layout manager complete the layout. Use a delayed post of 50 or 100 ms.
But also, you should use `scrollTo` from the RV and not from the layout manager.

0 is a valid position, it means that the adapter found the item at first position. If so, `scrollTo` doesn't produce any effect because the first visible item is already at that position. Which position did you expect instead?

Your `equals()` seems ok, it is used by the Java collections (in this case List), not by the Adapter directly.

**Comment by shymmq** [comment]
Thnak you for your support. `postDelayed()` with delay of 50ms works OK, but i will try to find a better way to do this as the delay is noticeable.

**Comment by davideas** [comment]
50-100ms is not noticeable. You can try even less, the importance is the layout manager completes the layout.
