### ISSUE TITLE
Weird shifting of list elements at startup

### ISSUE THREAD

**Issue by shymmq** [davideas/FlexibleAdapter#257]
![screencast](https://cloud.githubusercontent.com/assets/8517017/21467356/e6d02e46-c9ea-11e6-9a4e-7ca03c57e806.gif)

Weird thing is it only happens sometimes. From what i've noticed it works correctly first time i open the app, but it doesn't when the fragment containing the RecyclerView is getting recreated. Any clues as to what might be causing this?
I'm using `5.0.0-b8`.
note: animations in the attached screen recording were slowed down to 20%

**Comment by davideas** [comment]
@shymmq, that should a normal effect if the header items are added after the initialization. In beta8 the headers depend by scrolling animation, if disabled, headers will be insert with `notifyItemInserted` instead. You can read the comments of the methods.

I worked on that behaviour and removed the scroll animation dependency for the rc1.
So, I suggest to adapt your code to the current Snapshot, because by end of the year I will publish the rc1 that comes from this Snapshot.
To see the snapshot changes content read #39 last post, I also made a migration guide, that is better if you read it :-)

**Comment by shymmq** [comment]
Thanks, it seems to work now. Keep up the good work!
