### ISSUE TITLE
Is it okay to initialize endlessly scrolling adapter with null?

### ISSUE THREAD

**Issue by shymmq** [davideas/FlexibleAdapter#269]
I was wondering if I always have to add some starting elements in order to endless scroll to work?
Let's say I initialize my adapter with `FlexibleAdapter<IFlexible> adapter = new FlexibleAdapter<>(null);`
Then i set EndlessScrollListener on it, for example `adapter.setEndlessScrollListener(this, progressItem);`.
In this case, will onLoadMore fire on startup? In all examples i have seen there are some starting items.
Is this considered a good practice?

**Comment by davideas** [comment]
@shymmq, indeed, at the moment you need to bind something to trigger it (not the _progressItem_!), one item is necessary.
If I added `if (getItemCount() == 0) onLoadMore(0);` when setting the first time the progress, it will start automatically. But you can tell me better, since you are using it more than me: when adapter is empty at startup, better an implicit automatic start or a boolean settings?

However, this also works: your remote method at startup and also show the _progressItem_ with `mAdapter.addScrollableFooter(mProgressItem);`

**Comment by shymmq** [comment]
Thank you, that makes sense. I think that something like `adapter.loadMoreOnStartup(boolean b)` would be perfect. It should be set to `false` by default, though, so it doesn't break any old code.
