### ISSUE TITLE
FlexibleAdapter swiped item does not disappear

### ISSUE THREAD

**Issue by JeffreyLeeSpokeo** [davideas/FlexibleAdapter#270]
So I followed the instructions on "Swipe the front view" on this link:
https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Drag&Drop-and-Swipe

And I was able to get swiping to work with having a rear view during swipe left and swipe right. My layout is simple. I have rows of AbstractFlexibleItem stacked vertically on top of each other. When I swipe right or left, the front view disappears, but the rear view is still there. The space that the AbstractFlexibleItem was taking up was still there instead of having the item below it move up. Is that not one of the default features of the swipe view? Or do I need to do something else?

**Comment by JeffreyLeeSpokeo** [comment]
I found the answer. For the adapter you need to do stuff onItemSwiped. All I did was removed it from the dataset and called notifyDataSetChanged().

`
@Override
public void onItemSwiped(int position, int direction) {
    super.onItemSwiped(position, direction);
    dataSet.remove(position);
    notifyDataSetChanged();
}
`

**Comment by davideas** [comment]
@JeffreyLeeSpokeo, maybe was not clear from that wiki page, indeed I still need to review it.
But you have a specific listener you can implement instead of overriding the method: `OnItemSwipeListener` that extends also `OnActionStateListener`.

Up to you if you want use the listener or keep overridden the adapter method.

For removing the item you should use `removeItem()` only, without `notifyDataSetChanged()`.
Actually, what is dataSet object you wrote? (FlexibleAdapter has mItems inside which is a List object)

**Comment by JeffreyLeeSpokeo** [comment]
Sorry, I initialized dataSet somewhere else, but you are right. I learned later on that removeItem() was just a better solution.
