### ISSUE TITLE
Issues with empty expandable headers and dragging

### ISSUE THREAD

**Issue by djuelg** [davideas/FlexibleAdapter#287]
- Version: RC1
- Hardware: OnePlus 3T
- Android: 6.0 Marshmallow

---

Hey there,

my Application is using Expandable Sticky Headers and normal Section Items. Both item types can be added by the user with buttons. Both item types can be dragged and dropped. There are three (related) issues with empty expandable headers and dragging.

### Issue One
The last item in the list is a header. There are no subitems. It cannot be expanded on click. An empty header in the middle of the list can be expanded and collapsed even if it is empty. I tested in debugging mode wether the method expandView() or collapseView() get called. For the last item it is always the expandView() method. But this header should be expandable too, because I have to drag a section item into it. For the other header items it is working as expected.

### Issue Two
If I drop a section item beneath an expanded empty header the section item gets added to header as expected. If  I drop a section item beneath a collapsed empty header the section item gets added to the header. If I expand the header afterwards the section item is visible two times. If I try to collapse the header again an "Inconsistency Detected" execption is thown.

### Issue Three
If I load an existing list from the database containing an empty expandable header the header is always collapsed, regardless if I call adapter.expand() or settings in the HeaderItems constructor. I would like to have an expanded header at the startup to avoid issue two.

Have a nice day :)
djuelg

**Comment by davideas** [comment]
Hi @djuelg, I will try to quickly explain part of the Expandable API, did not write wiki on that yet.

**Issue 2 and 3**
- Empty expandable cannot be expanded, regardless the command you invoke.
- Sub items have to be added **only** in the list of the expandable item, then you can expand it, so there's no duplication if you do this. If you add section item directly to the adapter then it is considered independent from other sections.
- An expandable to be expanded must have property `expanded=false`, unless exceptions cases (which not important in your case now).

**Issue 1**
I did not understood well, as far as I did, dragging within expandable is really complicated, and should be taken a particular attention by the developer.
When you drag you will need to identify under which expandable the item is dragged, then if he stays in that position for 2 seconds you should expand. If it is empty and the item is released then you change the flag expanded=true, and then you add the item in the sublist.
You should also disable the autoScroll when you expand during dragging.
As said it is complicated.

Finally check that you have unique ID for `equals()` methods, otherwise Java List doesn't identify the items correctly as you expect. If you don't have unique ID, then use default java implementation `return this == o<`

PS. All those items are for presentation only, not database items.

**Comment by djuelg** [comment]
Okay thanks for you input!

I would like to be more precise on the following:
When I add an Expandable to the list and I don't add subitems to it, it is always collapsed. If I understood you right this is intended and cannot be changed. But when I add an Expandable to the list and I add one subitem, then expand the Expandable and then remove the subitem, the Expandable stays expanded even if it is empty. So there can be empty Expandables in expanded state.

For me it would be the best to have the ability to expand an empty Expandable.

**Comment by davideas** [comment]
@djuelg, suggestion: you can create and empty item to be added by default if the expandable is empty.
when all subitems are removed, I will evaluate if I can automatically, change the status.

**Comment by djuelg** [comment]
A bit ugly, but a "hidden item" should do it.

Have a great day :)

**Comment by davideas** [comment]
I close for now, if you need more help, on these questions, please reopen.
