### ISSUE TITLE
Dual headers for a section item

### ISSUE THREAD

**Issue by preyesm** [davideas/FlexibleAdapter#307]
Hi @davideas, I wanted to develop a google calendar kind of view, which has month name as main header and then weekname/date as secondary header for any section item. So whenever an event comes in it goes into specific header automatically. Can this be done with the current implementation of your library?

**Comment by davideas** [comment]
@preyesm, this library can support multiple header views, but only one can be sticky per time.
You can create an expandable item (with expandable=false by default) which is the main item(the month header possibly not sticky), then each child of the same week, has another header inside so that these can be sticky.
It's a bit complicated, you can give a try however.
