### ISSUE TITLE
Filter with multiple selection mode

### ISSUE THREAD

**Issue by IHNEL** [davideas/FlexibleAdapter#308]
Hi, 
I am using the Filter feature within Multiple Selection.  They work fine separately, but there are issue which can't persist selected item across filtering. for eg, if I select several items, then type a keyword for filter, then select some new items, then clear keyword. What I expected is the method `getSelectedPositions()` should return exactly index of selected items. Am i wrong in this situation? Could you please guide me how to achieve this ?

**Comment by davideas** [comment]
@IHNEL, or you select items or you filter, at least you can select items after filter, but you can't have selected items if you clear filter, because clearing filter will alter the selected positions.

What you want is to filter multiple times and keep the selection when occurring? For sure the ActionMode should not cover the SearchView, which actually it does in my demoApp.

**Comment by IHNEL** [comment]
Yes, after i clear the key string, the list of item changed and the selected items are not same with before.

I am creating a task management app and this is screen to select participants. User will open this screen with many contacts. They may search 'john' and select john, then search 'peter' to select peter. Both selected contacts must persistent.
Btw, this screen similar Whatsapp participants screen. I already add sticky header, fast scroller to my recycler view

**Comment by IHNEL** [comment]
@davideas Any idea to resolve this?

**Comment by davideas** [comment]
@IHNEL, what I can suggest is to override FlexibleAdapter method toggleSelection (I guess you call this method when user clicks on ViewHolder), so you can save and remove your own selection as item reference in your own Set (not List), and have a method called `getSelectedItems()` which returns always the list of the overall selections between the filters.
Also you need to override properly the method `isSelected()` so that it will not check the list of position but the set of items you saved.

I think it should work.

The Adapter is saving the positions of the current list, not the references of the items. I don't know if it's better or worst to have item references against positions.

**Comment by IHNEL** [comment]
thank you @davideas. Seems this is the only way, I will do this
