### ISSUE TITLE
How to find adapter position from outside of adapter

### ISSUE THREAD

**Issue by IHNEL** [davideas/FlexibleAdapter#311]
Dear,
I using this library to build my contact list. 
I want to show contact under groups that show first letter of inner contacts, e.g. group A contains all contact with name start by `A`. So, I use Sticky Header to display the groups.
For example I display 1000 contacts. For some reasons I want to update the View corresponds to the data-item at 500. Unfortunately, the Recycler view item at 500 doesn't display data-item 500. I guess the adapter counts header also.

How can I find the position of view item that is showing data-item at 500?

**Comment by davideas** [comment]
@IHNEL, either in you want to do programmatically or when user clicks on it (saved the reference somewhere or the ID), you work with unique IDs, and custom implementation of `equals()` method, so that when you call `getGlobalPositionOf(item)` that item can be found in the List and index returned.

You have to have the item object with the ID you want to update, the rest is done by Java itself when you call that method.

**Comment by IHNEL** [comment]
Hmm what i have is the index of data only. Mean the contact at index 500 of the contact array. Want to find the view item in the adapter for that item

**Comment by davideas** [comment]
@IHNEL, the array of data is your list? if so you have the object already with that ID inside, you just need to call `getGlobalPositionOf(item)`.
To have the ViewHolder, you can use the RecyclerView API.
