### ISSUE TITLE
Exclude item from update

### ISSUE THREAD

**Issue by henengel** [davideas/FlexibleAdapter#321]
Hi, I already have an open ticket, but since the is a separate question, I thought I would open a new one.
I have a recycler view with multiple item types. One of these types is DFP banners.
These specific items don't play well with a recycler view. Hence I would like to exclude them from updating. 
Is there any way to do so?
Thank you

**Comment by davideas** [comment]
@henengel, I was thinking something similar to your proposal: a new method for the item interface so it will get update if requested, but I need to review how the update is made, because now you get updates caused by headers redisplayed at the end of the process.

You can however try this:
Be sure to use _unique id_ for all of your items, so you can enable _stableIds_ in the Adapter constructor. Did this you can call `updateDataSet(new items)` with single notification disabled (`animate = false` by default) which means `notifyDataSetChanged` is invoked but RV is still able to recognise the unique id and notify only those changed.

**Comment by henengel** [comment]
I think using stable id's did the trick.
Again thank you very much.
I have quite a unique use case of your adapter. (7 view types with DFP integrated and other goods).
If you would like to use it in order to improve your project or/and you need more information about the issues open in ticket #314 , don't hesitate to contact me.
I hope I won't have to bother you again.
Have a good one.
