### ISSUE TITLE
How to handle onclick of a button inside header?

### ISSUE THREAD

**Issue by nidhiAscra** [davideas/FlexibleAdapter#326]
I am using library inside my application. My requirement is use different view header and items at different position. Using this code i am unable to handle onclick of the header view. but item's click event is beign handled inside Adapter class. Please do solve the issue,

**Comment by davideas** [comment]
Hello @nidhiAscra, thanks for the question. In this case, you do the following:

1) Override _FlexibleAdapter_ with your own _CustomAdapter_, and create a public field for the Callback interface that can be used in the View Holder when you implement the item. So you will instantiate only CustomAdapter from now on.
2) The constructor of the _CustomAdapter_ accepts the implementation of the callback.
3) The constructor of the View Holder accept your _CustomAdapter_ instead of _FlexibleAdapter_ so when you create the ViewHolder you cast the Adapter to _CustomAdapter_.
4) Inside the click listener of your button/image you can call the callback interface: `mAdapter.MyCallback`, where _mAdapter_ is a private field in the View Holder initialized in the constructor.
5) The implementation of the callback can finally be done in the Activity or the Fragment as a field or as implementation of the class.

**Comment by nidhiAscra** [comment]
Hi Davideas,
Thank you for the reply.
I am following same method for declaring and handling onclick event of a view inside adapter. It is handling properly for the view inside onBindViewHolder, but for the view inside onBindHeaderViewHolder the onclick event is not being handled. 
Here my header view is containing one button and a text. I am using your StickyTestAdapter and I have customize it as per requirement.
