### ISSUE TITLE
StickyHeader programmatically set backgroundColor

### ISSUE THREAD

**Issue by marbat87** [davideas/FlexibleAdapter#332]
Hi,

I'm trying the latest RC version 5.0.0-rc1
Android version 6.0.1

I need to set the background color on expandable header items programmatically.
I set it in:
`    @Override
    public void bindViewHolder(FlexibleAdapter adapter, ExpandableHeaderViewHolder holder, int position, List payloads) {
     ...
        holder.itemView.setBackgroundColor(MYCOLOR);
    }`

It works fine if headers are not sticky.
If I activate the stickyHeader in the adapter, when a header becomes sticky because of scrolling, the background color is lost and it becomes transparent.

Thanks in advance

**Comment by davideas** [comment]
@marbat87, can you try to use `holder.getContentView().setBackground()` only for header item?
Because of the mechanism a frame layout is inserted between the content header and the old parent.

You might want to use the `DrawableUtils` functions that are inside the library. So you will have the ripple effect as well.
