### ISSUE TITLE
Sticky headers in filtered list

### ISSUE THREAD

**Issue by tprochazka** [davideas/FlexibleAdapter#339]
Would be great if sticky headers will remain sticky also in filtered list.

**Comment by davideas** [comment]
I have re-enabled the possibility of this feature, since it seems to work after a fix related to this [commit](https://github.com/davideas/FlexibleAdapter/commit/efd2f228e76f709eaa0f8937222e831ca4be9986#diff-26353d6c0f5fb714881dd30a0c9454f3R5311) (issue 320).
However, if it creates issue again I will disable again. I tested but please do your tests as well in your apps.
