### ISSUE TITLE
Is there a workaround to use this lib with a cursor data

### ISSUE THREAD

**Issue by miroslavign** [davideas/FlexibleAdapter#358]
Is there a workaround to use this lib with a cursor instead of using a fixed list:
// Initialize the Adapter
FlexibleAdapter<IFlexible> adapter = new FlexibleAdapter<>(myItems);

I intend to use it for presenting contacts, lots of them, there may be 12k contacts so, 
I can not use a fixed list of 12k model items.

**Comment by davideas** [comment]
@miroslavign, I already analysed the Cursor in the issue #208.
Please test the demoApp with 10K-15K items using filter as well. I think it is quite fast. Why you cannot use a fixed list? From were they come from, DB or Net? Maybe LoadingMore feature could be useful to you?

**Comment by miroslavign** [comment]
Got it, 
tnx for a quick reply, I did not check that closed #208 issue myself.
We are using it from local database, using a fast scroller on the right side, and load more is currently 
not an option in our concept.

I have prepared custom items for presenting headers, and they are returned from cursor. For example, I am merging 4 cursors to get
1) section-1 header
2) section-1 items
3) section-2 header
4) section-2 items
So I have all the prepared items, but need to make headers sticky (for this first iteration).
![screenshot_20170508-094018](https://cloud.githubusercontent.com/assets/1773454/25794811/d7cb98d4-33d2-11e7-8751-862e0bdd57af.jpg)

**Comment by davideas** [comment]
@miroslavign, so are you preparing a separate list to provide to the Adapter or you have a final cursor?

For stickyHeader you need to set displayed the headers initially and activate sticky headers as well. Basically the headers are not added to the list since they are managed by the Adapter internally: you should add only the items with the header linked, because normally headers are not main items, just a separation of the groups/sections. At the moment you can't change the property yourself to set the fact headers are already shown.

**Comment by miroslavign** [comment]
I have a final merged cursor. It has interleaved data as pointed, so header-data-header-data.

It is not a problem for me to remove these two header item rows, and for normal data items, I can detect in code - from which section are the items... So that would be solved.

Anyway, in parallel, I am trying to resolve this first step (sticky feature) using pure Decoration. But long term, using your library for more features  would be more efficient for me to focus on other aspects.
Tnx
