### ISSUE TITLE
Swipe through Horizontal Direction

### ISSUE THREAD

**Issue by preyesm** [davideas/FlexibleAdapter#370]
Hi, thanks for the awesome library first. I want to know if there is a functionality to swipe through the list and get the current item position in view, in horizontal scrolling? 

I can have fast scroll where in after the scroll settles it would settle only on one view as my individual item's width is match parent and when i scroll slowly it should scroll one complete item in the list and I would need the position of post such scroll. 

I checked the method adapter.onItemSwiped and I am exploring ways to use this method to serve the purpose. But if there is a direct way to do from this library, kindly let me know :)yes
mail: preyes@agentdesks.com

**Comment by davideas** [comment]
@preyesm, thanks!
The library supports the horizontal scrolling and the vertical swipe, I could not have the time to test it properly with a demo. Also FastScroller is supported but still not fully tested by me in horizontal layout.

The Snap feature you describe is not inside my library because it's officially supported by Support Library version 24.2.0. Check this page: https://rubensousa.github.io/2016/08/recyclerviewsnap.
Thanks about this, I would like to add it to the demoApp here :+1: 

Read the Java doc of the method `onItemSwiped()`. (Just a reminder, all methods have Java doc).
You also have `onActionStateChanged()` and `FlexibleViewHolder#onItemReleased()`.

**Comment by preyesm** [comment]
Great buddy, I did not know Play store is the answer for all the layout one doesn't the name off but needs them precisely. SnapHelper has come to my rescue. Thanks.

**Comment by davideas** [comment]
You can check also this one, it seems very good.

https://github.com/TakuSemba/MultiSnapRecyclerView
