### ISSUE TITLE
Create a list with different AbstractFlexibleItems

### ISSUE THREAD

**Issue by huangwaylon** [davideas/FlexibleAdapter#405]
I would like to create a list with various sections. However, I need each section to contain rows of a different item type. For instance, one section would be called `restaurants` and would contain rows with restaurant names and addresses. Another section would be called `tourist sites` and would contain rows with location, hours of operation, and description. Overall, these rows contain placeholders for information that won't overlap. 

Perhaps I'm not seeing it, but `FlexibleAdapter` doesn't provide a way to create an adapter that holds different objects that all extend `AbstractFlexibleItem`, right? If it did, I would create a class for each row type item - like restaurants and tourist-sites, and then add them to each section as needed.

Another possibility might be to create a single object extending `AbstractFlexibleItem` and inflate a different view in `createViewHolder` depending on the item type. However, this seems messy as this one class would contain information about all the different row types - for example both restaurants and tourist sites.

My overall question is, how should I approach this problem with Flexible Adapter?

Thank you!

**Comment by davideas** [comment]
@huangwaylon, thank you for the question that allows to clarify this point of multi view types.
Because, this adapter is backed by a List, Java wants 1 type for its list, but with Java you can also extends the object indefinitely. Each type will be automatically created and bound once added to the list, but all extends an abstract class with common fields, I imagine it as ID, name, description etc... depends by your use case.

In the end, you can add as many view type and you can combine them as you wish:
```
Header1 extends AbstracHeadertItem that extends AbstractItem implements IFlexible.
SectionableA1Header1 extends AbstractItem
SectionableA2Header1 extends AbstractItem
Header2 extends AbstracHeadertItem that extends AbstractItem implements IFlexible.
SectionableB1Header2 extends AbstractItem
SectionableB2Header2 extends AbstractItem
etc..
```
When you create all those objects you will add them to the list defined as `List<AbstractItem>`. This list is the only one, provided to the adapter.

When you want to get an item from the adapter, unfortunately you still need to check its type before you cast it to the correct item. Of course, you will cast it only if you need a specific method of the type you want. If you need to access to the ID only, you don't need to cast it.
Either you check with a (switch case) which instance the object is. Either you check which itemType the object is.

Others adapters can maybe help you to separate multi view type with different sub-adapters but they don't provide all the functionality I developed. For the moment this is the architecture of this adapter.

**Comment by huangwaylon** [comment]
Thank you for your suggestion! I have successfully implemented it using the advice above. Sub-classing made things more logical and organized!
