### ISSUE TITLE
Expandable Item Modify without clicking

### ISSUE THREAD

**Issue by sprengerst** [davideas/FlexibleAdapter#407]
I have a multi level list (3 levels): 

- main
- -  sub
-  -  -  subsub 

Now I only want to change a property of one of mine subsub items, without clicking on it. So somehow make something like **getSubSubItemById(String id)**. 

Is it possible to get an Item by its ID and modify it without exchanging the whole list?

Also I think it would be interesting to know if there is the possibility to "scrollToSubSubItemById" somehow.

Best & thanks for this awesome lib,
Stefan

**Comment by davideas** [comment]
Hello @sprengerst, thanks for compliments.

Regarding to your question, you need to distinguish 2 cases the expandable is _expanded_ and _not-expanded_.
If not expanded, for the adapter it's impossible to retrieve anything because that item (not shown) is not in the adapter list (it will return null or -1 for position), but in the sublist of the Expandable!
If your use case is to do this modification often, why don't you create a method in your expandable to get your subItem by ID?

But, if it is expanded, you also need calculate the position before calling to call `notifyItemUpdate()` OR simply `updateItem()` by passing the same modified item instance to be rebound for the user, the position is found internally for you...
However, to know the position, you must anyway implement the `equals` method of the subItem.
Finally, for the position you can also call `getGlobalPositionOf()`, but again, only if it is visible.

If you extends AbstractExpandableItem, check the already iplemented methods inside.
For expandable methods documentation, please check the new Wiki page for expandable.

**Comment by sprengerst** [comment]
Hi @davideas , first at all thanks for your response.

>> _If your use case is to do this modification often, why don't you create a method in your expandable to get your subItem by ID?_

I think this is the main problem for me here, because as I understood it, I don't have any possibility to keep an instance of mItems after handing my list over to the FlexibleAdapter. In the constructor of FlexibleAdapter the handed over list ist copied and I can't see a getter for getting the "real used" item list? I don't know how I should keep a reference or obtain the Expandablelist.

`
	public FlexibleAdapter(@Nullable List<T> items, @Nullable Object listeners, boolean stableIds) {
		super(stableIds);
		// Copy of the original list
		if (items == null) mItems = new ArrayList<>();
		else mItems = new ArrayList<>(items);  // I THINK THIS LINE KILLS THE REFERENCE
		......
	}
`

Thank you for your support

**Comment by davideas** [comment]
@sprengerst, you have methods to get the expandables and subitems, you also have the new methods in Rc2 to get the entire list (in only read mode). But please you should read migration wiki page as well.

Also the list is a copy not the content! You should know this if you work in Java.

**Comment by davideas** [comment]
@sprengerst, you have 2 ways in Java 7 to get your item from a list: you scan the list and break when you find it OR having well implemented the `equals` method, when you have only the ID, you allow Java to do it by creating an empty object with only the ID inside, then you pass this empty instance to get the index of that item then you finally call get(index) and you have your original instance with all content.
Probably is better to scan the list.

But many utility methods for expandable items are already implemented others for your use case you can implement yourself.

**Comment by sprengerst** [comment]
@davideas Thanks for bringing this to my attention! I didn't knew that ArrayList(Collection<? extends E> c) is behaving like this now things clear up. I thought that I would lose the original reference. Didn't know that changes affect each other list content.
