### ISSUE TITLE
removeItem (position, payload)

### ISSUE THREAD

**Issue by rusxakep** [davideas/FlexibleAdapter#429]
In removeItem function and in some other, I think payload should be some interface type, but not common Object for reduce coding errors.

What do you think about it?

**Comment by davideas** [comment]
@rusxakep, the payload is passed only to the parent item, such as headers and expandables when they are notified change. If the item to remove doesn't not belongs to any of those parents, it is useless.

Keeping this in mind, the payload is passed to the `notifyItemChange()` function only and it is returned in a list of generic objects in `bindViewHolder()` (of the parent). So, no, it can't be a specific interface, since it will be returned as list of objects anyway by the RecyclerView.
