### ISSUE TITLE
Delete some items from 'for' cycle

### ISSUE THREAD

**Issue by rusxakep** [davideas/FlexibleAdapter#432]
Classical problem with delete items in cycle's:

```
for (int i = 0; i < adapter.getItemCount(); i++) {
    Item item =  adapter.getItem(i);
    if (item.getId() > 5) {
        adapter.removeItem(adapter.getGlobalPositionOf(item));
    }
}
```

How to delete some elements in adapter correctly? No iterator or something else :(

I think about workaround like replace remove to selectItem and at finally removeSelectedItems...

**Comment by davideas** [comment]
@rusxakep, nothing interesting from the series functions `remove*()` ?

**Comment by davideas** [comment]
@rusxakep, please check `removeRange()`, which is same as you are doing, `removeAllSelectedItems()` if you previously have selected items.
Iterable cannot be under user control, because there's much more to do behind.

**Comment by davideas** [comment]
@rusxakep, Or you can start from end and `removeItem(position)` directly with no `getGlobalPositionOf()`.

**Comment by rusxakep** [comment]
After removeItem(position) adapter change getItemCount().

Try use this test - create adapter with some items and try delete all items by removeItem(position). You can't do it in 'for' cycle. At end, some items still in adapter.

**Comment by rusxakep** [comment]
@davideas, About getGlobalPositionOf(): this is from my code with networked async tasks (delete item). After task end, position of current item maybe changed by other tasks (delete item).

**Comment by davideas** [comment]
@rusxakep Ok about the global position, but be aware that _notifyXXX_ functions can be called only from main thread.

Yes of course, you grab the wrong index while removing items, that's why you start from end. Alternatively you can use `getCurrentItems()` that is an unmodifiable view.
I've committed something, please check.

**Comment by rusxakep** [comment]
@davideas non intuitive name for getCurrentItems(). :-) Better use function like getItems() without any 'unmodified' prefixes.

BTW, up to this point, I guess its function for some items with some sort prefixes, like getVisibleItems and so on. Thanks for advice.

**Comment by davideas** [comment]
@rusxakep, cannot release the internal reference of the List, user has access to it as a snapshot.

For the current visible items, is more subtle concept, what does it means visible? In reality it is `getAllBoundViewHolders()` because RV bounds more items than ones really visible on the screen, normally.

**Comment by rusxakep** [comment]
@davideas No, I do not need get visible item, is for example. Some mental association for getCurrentItems function name. Forget it.

getImmutableItems()?

**Comment by davideas** [comment]
ehehe, I know. Ok, let's close this ticket.
