### ISSUE TITLE
FlexibleUtils.highlightText with multi-span in same string

### ISSUE THREAD

**Issue by jrcacd** [davideas/FlexibleAdapter#443]
How to highlight multiple searched strings in the same view?

**Comment by davideas** [comment]
@jrcacd, you can't with the current solution, need to enhance the function.
Thanks for the hint!!

**Comment by davideas** [comment]
Since I was curious I tried already. But I did much more: I've improved the span text by skipping the consecutive text.

#### Examples:

###### searchText / to span: 2
- Item **2**2
- Item 1**2**3**2**
- Item 1**2**24

###### searchText / to span: 22
- Item **22**
- Item 1232
- Item 1**22**4

###### searchText / to span: te
- In**te**rnal I**te**m
- I**te**m **te**text

**Comment by jrcacd** [comment]
Very good
