### ISSUE TITLE
About FlexibleViewModel Identifier

### ISSUE THREAD

**Issue by alittlecup** [davideas/FlexibleAdapter#491]
i have read the liveData wiki and made a demo , but i have a question . i know the identifier is the stream start , to getSource , map source to listItems . 

in my project , i have more than one liveData to getSource , how to set Identifier?

such as a filter tab include name , age, location, gender ..       them all is LiveData,   one of them change , i should getSource, how to set the Identifier ?

Make a class contain them and set the class to LiveData? or other?

sorry for my english , it's not well  :)

**Comment by davideas** [comment]
@alittlecup, you can have an inner static class if the ViewModel class (not livedata class) named `Identifier` with the fields you need (ids, _name, age, location, gender_). But the identifier for you contains also some filter fields: you load the same model list from the same repository using different DAO queries (different functions) for different filters.

In the google live data example, they use an Identifier class to uniquely identify a record if the primary is multiple, you have to do the same. Instead of only a Long id, shown here in the wiki, you have a class with fields that identify uniquely a record, plus some filter fields.

As you see in the `getSource()` implementation you receive the same object of type `Identifier` with all the previous fields for the repository function.

I hope to have answered at your question.

**Comment by alittlecup** [comment]
Thanks a lot for your answer , I will create a class to hold the different filters
