### ISSUE TITLE
doInBackground() of FilterAsyncTask is not called.

### ISSUE THREAD

**Issue by shomin1983** [davideas/FlexibleAdapter#528]
I found the FilterAsyncTask() is called by default AsyncTask.SERIAL_EXECUTOR in HandlerCallback class.
`mFilterAsyncTask = new FilterAsyncTask(message.what, (List<T>) message.obj);
mFilterAsyncTask.execute();
`
If the default executor is blocked by another asyncTask, doInBackground() of FilterAsyncTask is not called util another asycTask finish task.

I think the FilterAsyncTask should be executed by calling **AsyncTask.executeOnExecutor**(Executor exec,
            Params... params).

**Comment by davideas** [comment]
@shomin1983, why do you think the THREAD_POOL_EXECUTOR is better?

_From official documentation:_ Allowing multiple tasks to run in parallel from a thread pool is generally not what one wants, because the order of their operation is not defined. For example, if these tasks are used to modify any state in common (such as writing a file due to a button click), there are no guarantees on the order of the modifications. Without careful work it is possible in rare cases for the newer version of the data to be over-written by an older one, leading to obscure data loss and stability issues. Such changes are best executed in serial; to guarantee such work is serialized regardless of platform version you can use this function with SERIAL_EXECUTOR.

**Comment by shomin1983** [comment]
If FilterAsyncTask must be executed  in serial, the THREAD_POOL_EXECUTOR is not a well solution.
I think you could pass your serial executor(MY_SERIAL_EXECUTOR) to AsyncTask.executeOnExecutor() instead of AsyncTask.SERIAL_EXECUTOR.
If AsyncTask.SERIAL_EXECUTOR is blocked by unexpected AsynTask usage, the FilterAsyncTask.executeOnExecutor(MY_SERIAL_EXECUTOR) will not be influenced.

You could do a testing for current FilterAsyncTask usage.
e.q
new AsyncTask() {
        @Override
        protected String doInBackground(Void... params) {
            Thread.sleep(30000); // 30 secs
        }
    }.execute();

new FilterAsyncTask(message.what, (List<T>) message.obj).execute().

The doInBackground() of FilterAsyncTask will be called 30 seconds later.

**Comment by davideas** [comment]
Lot easier if I put `THREAD_POOL_EXECUTOR` since it is cancelled anyway before another execution.
