### ISSUE TITLE
ViewModel, LiveData and Sticky Headers

### ISSUE THREAD

**Issue by Johnny2212** [davideas/FlexibleAdapter#529]
I have looked through the wiki and the sample app, but I still have a problem.

Is it possible to add Sticky Headers when working with LiveData from Android Architecture Components?
If it is possible, do you have an example of how to implement this?

Thank you!

**Comment by davideas** [comment]
@Johnny2212, Yes it's possible, we have to map the items for the adapter from their original models coming from LiveData. Adapter configuration remains unchanged, so once we have the LiveData, we map its content to a list suitable for the Adapter (with IFlexble item type series).

The library [LiveData](https://github.com/davideas/FlexibleAdapter/wiki/Extensions-%7C-LiveData), in **beta**, should simplify the process but I can't provide yet a good example since I'm trying to make it simpler. As it is now, this small library is _not_ very intuitive and not even comfortable to use sincerely.

The idea is to implement a function that does this transformation: `adapterItems = viewModel.map(models())`. For now you can create this function yourself.

**Comment by Johnny2212** [comment]
That's great news! Thank you for this awesome library!

Do you have an estimated time when LiveData will come out of beta, or be at a point where you are "happy" with it?
