### ISSUE TITLE
How to display FastScroller on the left side?

### ISSUE THREAD

**Issue by meness** [davideas/FlexibleAdapter#538]
```xml
<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@id/btn_select_contacts"
        android:layout_below="@id/toolbar_container">
        <android.support.v7.widget.RecyclerView
            android:id="@+id/rv_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:verticalScrollbarPosition="left"
            android:orientation="vertical"
            app:layoutManager="android.support.v7.widget.LinearLayoutManager" />
    </FrameLayout>

    <include layout="@layout/fast_scroller" />
```

```xml
<eu.davidea.fastscroller.FastScroller xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/fast_scroller"
    android:layout_width="wrap_content"
    android:layout_height="match_parent"
    android:layout_above="@id/btn_select_contacts"
    android:layout_alignParentLeft="true"
    android:layout_alignParentStart="true"
    android:layout_below="@id/toolbar_container"
    app:fastScrollerAutoHideDelayInMillis="1000"
    app:fastScrollerAutoHideEnabled="false"
    app:fastScrollerBubbleEnabled="true"
    app:fastScrollerBubblePosition="center"
    app:fastScrollerIgnoreTouchesOutsideHandle="false"
    tools:visibility="visible" />
```

I want to move the scrollbar to the left side of screen, it is on the right side by default, setting `verticalScrollbarPosition` doesn't work

**Comment by davideas** [comment]
@meness, I don't know if it will work, but you can try to override the drawable `fast_scroller_bubble.xml` (you can find it in the library) so you change the corners radius for left layout. And also the layout library_fast_scroller_layout.xml

Probably better:
Or you can create your own views and to set them with `FastScroller.setViewsToUse` before setting the FastScroller instance to the adapter, otherwise if will be too late, and the internal views will be used.

If it doesn't work, you need to create your own delegate, take an inspiration from FastScroller.Delegate object, where you specify your own views and do more sophisticated stuff.

**Comment by meness** [comment]
@davideas I did them but the results were not as I expected. I need to move the scroll to the left and also the bubble shape rotate without rotating the text inside
