### ISSUE TITLE
Gradle Error: Cannot create variant 'android-lint' after configuration ':flexible-adapter:debugRuntimeElements' has been resolved

### ISSUE THREAD

**Issue by MohammadNsr** [davideas/FlexibleAdapter#579]
Hallo 
i have android studio 3.1 and am trying to run the code but im getting this error:
Cannot create variant 'android-lint' after configuration ':flexible-adapter:debugRuntimeElements' has been resolved.

any idea, how to solve it?

**Comment by davideas** [comment]
This is due to new Gradle plugin when AS gets updated that goes in conflict with javaDoc plugin.
I've just updated the scripts with the new versions.
Let me know if it is fixed.

**Comment by MohammadNsr** [comment]
thank you very much. it work like magic.
i have a question here please.
my app will have a lot of items, say 1200. as an expert, would you say, that recyclerview will manage these items well and it will scroll easyily?
i have already listview and want to replace it with recyclerview.

**Comment by davideas** [comment]
@MohammadNsr, it depends how much heavy are those elements. But if you already have those number, I expect an increase of the performance because, by default, it should be faster: it recycles and reuses the Views not visible anymore to the user, without recreate all the view objects.
When you update the elements you can do with the `DiffUtil` or with the _internal calculation_ or with `notifyDataSetChanged()`. Up to you.
Follow also the #577 discussion.

**Comment by MohammadNsr** [comment]
Thank you. I will try to do the recommendations

**Comment by josemiguelmoreno** [comment]
Greetings, what would be the solution to the issue of the javaDoc conflict of the project or error module?

**Comment by josemiguelmoreno** [comment]
thank you very much and I could solve it

**Comment by midhunhk** [comment]
@josemiguelmoreno could you let me know how you solved it. I am also facing the same issue

**Comment by davideas** [comment]
@midhunhk, pull.

**Comment by midhunhk** [comment]
Hi @davideas , I'm working on a personal project and facing this issue after upgrading AS. Could you let me know what the fix that was provided or the checkin.

**Comment by samiazar** [comment]
Hi @midhunhk, I had the same issue with another library as you have.
I could resolve that with replacing this line:
`classpath = files(variant.javaCompile.classpath.files) + files(ext.androidJar)`
with:
`        doFirst {
            classpath = files(variant.javaCompile.classpath.files) + files(ext.androidJar)
        }`,
as @davideas said "This is due to new Gradle plugin when AndroidStudio gets updated that goes in conflict with JavaDoc plugin", If you have Javadoc task you must be able to find the same line

**Comment by jude07** [comment]
@samiazar how do I find this line:
 classpath = files(variant.javaCompile.classpath.files) + files(ext.androidJar)?

**Comment by samiazar** [comment]
@jude07 as I said before, one possible option for this issue depends on Javadoc tasks.
If you have any JavaDoc tasks on your project or maybe on another third-party library, You can find this line in build.gradle of that project.

**Comment by HemendraGangwar** [comment]
Thanks so much. It works for me by replacing

doFirst { classpath = files(variant.javaCompile.classpath.files) + files(ext.androidJar) }
to 
classpath = files(variant.javaCompile.classpath.files) + files(ext.androidJar)

The error has finally gone. :)
