### ISSUE TITLE
how to display the selected state of selected item

### ISSUE THREAD

**Issue by MohammadNsr** [davideas/FlexibleAdapter#589]
How can i display the selected state of an item by clicking it?
i did not find explanation in the wiki.
should i solve it alone or there is a solution within the felxibleAdapter Librariers?

**Comment by davideas** [comment]
This is well explained in the Wiki. Please use `ActionModeHelper`: In the moment we talk about selection, we are also talking about multi-selection because we manage a list.
The selection of an item is based on several parts, actually: an event registered on a position where the adapter is listening, the saving of selected position in the adapter, the view activation, the item binding if the position is selected, etc...
