### ISSUE TITLE
Adding OnItemClickListener() with FlexibleAdapter.addListener is confusing when you have section headers

### ISSUE THREAD

**Issue by NLLAPPS** [davideas/FlexibleAdapter#604]
I find it confusing or perhaps I should say error-prone because OnItemClickListener() is triggered whether user taps on an actual item or header. This could cause crash unless you specifically check which item is clicked with instanceof. It also swallows any on click listeners you might have in header holder.

Would it be better idea to distinguish OnItemClickListener and have 2 seerate ones like OnItemClickListener and OnHeaderItemClickListener?

This is just a thought, I do not have any experience with API design.

**Comment by davideas** [comment]
Possible names are infinite. Yes, we are managing a List<OneTypeHere>.

**Comment by christophehenry** [comment]
This answer is disappointing. Using `getItems()` or `getCurrentItems` actually throws a class cast exception when using `FlexibleAdapter` in combination with `AbstractSectionableItem` since `mItems` list also hosts headers which are not of type `AbstractSectionableItem`. You clearly rely on Java's generics flow to make this work since `mItems` is declared as a list of `IFlexible<VH extends RecyclerView.ViewHolder>` but, when queried, the JVM forces the items to cast to `AbstractSectionableItem<VH extends RecyclerView.ViewHolder, H extends IHeader>` even if the item is of type `IHeader`. This is clearly not a correct design and should be handled to me.
