### ISSUE TITLE
FastScroller scroll bar sync delay

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#605]
@davideas Now the Item position is at the top, when the Item scrolls down a distance, the position of the scroll bar does not change
![image](https://user-images.githubusercontent.com/10644057/39645147-ec413536-5009-11e8-917f-c2380e9555ae.png)
![image](https://user-images.githubusercontent.com/10644057/39645118-d75b8b6c-5009-11e8-904a-31022e25c9b3.png)

Scroll bar changes when Item scrolls a long distance, But I can be sure that the above problem is not because of too many items, Because when I continue to scroll down, the scroll bar changes slightly, I feel the synchronization delay of scroll bars may be related to `app:layout_behavior="@string/appbar_scrolling_view_behavior"`, although `appbar_scrolling_view_behavior` is set, but the FastScroller not remove the excess height for scroll bar, causing the first scroll sync delay.
![image](https://user-images.githubusercontent.com/10644057/39645494-2264a93a-500b-11e8-8ad3-52818833d429.png)

**Comment by davideas** [comment]
@tcqq, thank for this issue, I see it.
The FastScroller comes from another library. I verified the issue comes from there, and is still there! The calculation is done in `setBubbleAndHandlePosition(y)` and the effect is more visible at the increase of the items, the handle doesn't move along with the positions when at the top or at the bottom. Indeed it is caused by the height of the handle.

It will take some time to fix the calculation, however it's still usable, so it has low priority.

**Comment by davideas** [comment]
It should be fixed now, can please you check? Lines 427-429.

**Comment by tcqq** [comment]
@davideas Hi, I tested it, this problem looks has been fixed.
