### ISSUE TITLE
Custom Sticky Header

### ISSUE THREAD

**Issue by athul131** [davideas/FlexibleAdapter#615]
I tried adding a custom Sticky header by adding a layout
![screen shot 2018-05-29 at 11 06 13 am](https://user-images.githubusercontent.com/18029460/40639778-66fb88ce-6330-11e8-95e6-ef8296103eee.png) - 

You Have mentioned custom sticky header layout can still be added.

![screen shot 2018-05-29 at 11 07 28 am](https://user-images.githubusercontent.com/18029460/40639799-80c0b27a-6330-11e8-950d-cc1102738bac.png)

After adding these View group in layout i appended this in the adapter using
` .setStickyHeaders(true,(ViewGroup) getView().
                        findViewById(R.id.stickyHeaderViewGroup))`

![screen shot 2018-05-29 at 11 06 02 am](https://user-images.githubusercontent.com/18029460/40639834-c9655d1e-6330-11e8-9463-1862af08e3ad.png)

Everytime I touch the layout on just move them up or down the custom elayout disappears and shows the default header. This default header becomes sticky after that.

Tasks 
1- How to prevent custom sticky layout from disappearing
2- How to add the header data(Title and Sub title) which should be the sticky header to that custom sticky layout.
3- what is the mistake which is being done by me?

It would be helpful if you could explain me this and Fix this issue.

**Comment by athul131** [comment]
Here are The layout screen
![screen shot 2018-05-29 at 11 06 02 am](https://user-images.githubusercontent.com/18029460/40640240-d2d5a820-6332-11e8-905a-d4a28c8b188c.png)
![screen shot 2018-05-29 at 11 06 13 am](https://user-images.githubusercontent.com/18029460/40640244-d6caa46c-6332-11e8-83e6-d1ca88ba8b08.png)

**Comment by athul131** [comment]
Here are the layout screenshot
![screenshot_1527573179](https://user-images.githubusercontent.com/18029460/40640264-efeb7ff2-6332-11e8-9a54-37e7cf046cb6.png)
![screenshot_1527573184](https://user-images.githubusercontent.com/18029460/40640266-f028a3b4-6332-11e8-987e-f928bec4b2bf.png)

**Comment by athul131** [comment]
Any help would be very much appreciated!. Kind of stuck with this for few days.

**Comment by davideas** [comment]
@athul131, when you add your custom layout container you should see this log line: _User defined StickyHolderLayout initialized_. This container will host the headers in the list when reach the top.
What is your use case?

If your intent is to have a fixed and permanent layout, you have 2 options:
- Don't use IHeader item in the list, just put your layout on the above of the RecyclerView.
- Create a single IHeader and add it to the top, set headers visible and enable sticky header, then you cannot use more headers any more, otherwise those items will change content in the sticky layout.

If you want a custom sticky header container with `android:layout_width="wrap_content"` it changes size according to the content of the new header, Then you need a custom empty container.

PS. Remove the `<include>` below the RV: it's clearly written to not use it.

**Comment by athul131** [comment]
Please tell how to make header display with custom layout whrn it becomes sticky.

**Comment by athul131** [comment]
I want the container with an image and different font styles.
Its different from header view.
As per my requirement the sticky header has a different layout. Normal header and sticky header differ from each other in layout.

**Comment by davideas** [comment]
@athul131, well I think I already answered to you, you can't, because that is an _empty_ container.
You can try to change the header content once it is sticky.

**Comment by athul131** [comment]
As in screenshot shown in above comments.. The header which shows expandable two level... It layout design should  change when it becomes a sticky layout.

**Comment by athul131** [comment]
I tried doing it like that.. But changing the design with respect to sticky header change interface is causing a lag when i do a fling of recycler view

**Comment by athul131** [comment]
There is a lag when i change the background

**Comment by davideas** [comment]
@athul131, what you need is a special routine that maps your inner views into new ones. I'm sorry for you, but I do not have. Nothing to do.
