### ISSUE TITLE
EndlessScrollListener with Expandable HeaderItems

### ISSUE THREAD

**Issue by chrisonline** [davideas/FlexibleAdapter#623]
I just started using EndlessScrollListener, but I don't get it to work.

My List looks like this:
Header "1"
SubItem 1
SubItem 2
SubItem 3
SubItem 4
Header "2"
SubItem 1
SubItem 2

If I load **ALL** Data to the adapter i will do this:
Create the **Header Item "1"** and add to the Header item all **4 Subitems**.
Create the **Header "2"** and add to this Header Item all **2 SubItems**.

Now I will add both "Headers" to an ArrayList of type IFlexible.
This arraylist contains 2 items (the header items).

So now I want to implement the EndlessScrollListener with onLoadMore mechanism.
For example with count of 3.

I read **3 data rows** from my database:
Create the Header Item "1" and add to the Header item the 3 Subitems read from the database.

Now I will add this to an ArrayList of type IFlexible and call onLoadMoreComplete() with the data --> Works!

**Scrolling** happens and I get again **3 data rows** from my database:
If I create **again** the **Header Item "1"** and add the **last missing Subitem**. 
Call onLoadMoreComplete() with the data of ArrayList **of 1 entry** (the header item with the subitem).
Now I get two Header Items in my list --> Not Good!

So how should I add the missing item under the Header Item "1" because I normally add only the Header Items to the list and the Header Items have the subitems saved?

**Comment by davideas** [comment]
@chrisonline, try to give the same instance of the header you already have. I'm sure you know which header type belongs to the last loaded item, so you find it and assign it to this item.
Sorry, but for my point of view, this is depending on your use case to load sub-items separately instead of loading all sub-items for that header.
How many items are we talking about? Maybe the approach to take might be to load all sub-items every time you expand and NOT the endless. I do not know, I can't help very much.
