### ISSUE TITLE
Add a line separator/divider below each header

### ISSUE THREAD

**Issue by Shailevy** [davideas/FlexibleAdapter#648]
Hi,
Questions, How do you suggest I add a line at the bottom of section ?

The easiest approach I found was adding the line at the top of the header layout and then in the HeaderItem just adding: 

holder.mSeperator.setVisibility(position == 0 ? View.GONE : View.VISIBLE);

But this approach leaves the line visible when the header becomes sticky.

I was wondering if there is a "correct" approach I should try

**Comment by Shailevy** [comment]
Please find the time for a quick reply on this, I know it's hard to maintain a popular library and I appreciate the the Amazing work you are doing.
I just need you to point me to the correct approach before I go and make a pull request with too many changes.

**Comment by davideas** [comment]
@Shailevy, 2 options:
- Check if the header position matches with `getStickyPosition()`.
- Write your own Decorator using the logic I've written in `FlexibleItemDecoration.applySectionGap()`

PS. I'm sorry but in general I don't have mind anymore in this period to follow these issues.

**Comment by tcqq** [comment]
I tried `getStickyPosition()`, I don't know how I should get the position of the Header above and below the "C" Header, because the returned values are not in order (0, 1, 2, 3).

How should I achieve the divider for the following effects?
![mio-design 2fassets 2f1us53isyabmg3sfnhk2sroci8qgnggkmk 2flists-controls-expandable-open](https://user-images.githubusercontent.com/10644057/44955722-ad6d4580-aeea-11e8-9d43-b16f81fc375b.png)
