### ISSUE TITLE
Basic use case with sections

### ISSUE THREAD

**Issue by zosocanuck** [davideas/FlexibleAdapter#65]
Hi,

Any pointers on how to get a basic sections use case going?  I'm trying to create a recylcerview pulling based on static data with 10 categories and about 30 items.  I'm following the examples in the dev branch example app, but any help would be appreciated.

Regards,
Ivan

**Comment by davideas** [comment]
Hello @zosocanuck,

You said that data is static, that means it doesn't change if some events occurs while the RV is shown? and 30 items each section?
You can follow the wiki page for headers and sections, and choose the use case 1, which is the most simple to use: You can create `ISectionable` items by setting the same `IHeader` for same section; Add the items to the Adapter list; Call `setDisplayHeadersAtStartup()`.

PS. I've just committed some improvements in **dev** branch.

**Comment by zosocanuck** [comment]
Correct, I've created a product class which could mimic 
```
SimpleItem extends AbstractExampleItem<SimpleItem.ParentViewHolder>
		implements ISectionable<SimpleItem.ParentViewHolder, HeaderItem>, IFilterable, Serializable {
```

I have a ProductFragment which now sets an adapter of MyProductViewAdapter

`public class MyProductRecyclerViewAdapter extends RecyclerView.Adapter<MyProductRecyclerViewAdapter.ViewHolder> {`

So I would then change MyProductRecyclerViewAdapter to extend FlexibleAdapter?

**Comment by davideas** [comment]
You can also extend `AbstractSectionableItem` for the `Product` item. It should be simpler for you, because already implement the common methods for the header.

Regarding, the Adapter, you extend to `FlexibleAdapter`, correct.
You will see that you will have to give a parameter to the signature (the most common type of all items): Header type and Sectionable type both extends `AbstractFlexibleItem`, so you should use this signature `extends FlexibleAdapter<AbstractFlexibleItem>` (as in my `ExampleAdapter`) and implement the constructor properly.

In the end, your Fragment/Activity should implement the listeners your use case foresee.

Regarding the creation and binding the ViewHolders, my example shows how to use the METHOD A or the METHOD B (always in `ExampleAdapter`).

**Comment by davideas** [comment]
@zosocanuck, do you still need support on this issue?

**Comment by zosocanuck** [comment]
No this can be closed.  Slowly learning by trial and error :)
