### ISSUE TITLE
How to use search filter with multiple selection - also with screen rotation support

### ISSUE THREAD

**Issue by ShahoodulHassan** [davideas/FlexibleAdapter#668]
The sample app doesn't let the Activity destroy on screen rotation as declared in manifest by `android:configChanges="orientation|screenSize"`. This is something not everybody would like to do.
There IS code defined in `onSaveInstanceState` and `onRestoreInstanceState` but it seldom gets used. Having said that, for many of the features, screen rotation is supported if we simple follow the code defined in above two method but it doesnt work in the case I'm highlighting...it rather fails badly.
Use case: Im using a list with Sections & Headers. I want to delete some items that contain the text 'test' in them. So, i apply a filter using searchView and get, lets say, 5 such items. Then I long click any of these to initialize action mode. Then I select 3 of them by clicking each. Now if I rotate the screen, the following happen:
1. Action mode is re-initialized (Expected behaviour)
2. searchView is not iconified and contains the search string (Expected behaviour)
3. I get only those 5 filtered items with 'test' highlighted (Expected behaviour)
4. Number of selected items is rightly shown in action mode bar. (Expected behaviour)
5. Only the first one of those has selectable background though **(Unexpected behaviour)**

And yeah, I'm using the same code as found in onSaveInstanceState, onRestoreInstanceState and onPrepareOptionsMenu methods of the MainActivity.

Can someone tell me how to achieve above mentioned objective? I've spent a lot of time on understanding this cool library and just don't wanna dump it just like that.

Any help would be a great help!

Thanks

@davideas
@tcqq

**Comment by tcqq** [comment]
@ShahoodulHassan I added the save and restore code in this way, and now when I rotate the screen,can properly restore the selection state.
![image](https://user-images.githubusercontent.com/10644057/45270231-940d6000-b4cd-11e8-93a0-22b47363053f.png)

**Comment by ShahoodulHassan** [comment]
U r probably talking about cases where only selection mode was turned on when screen was rotated.

My use case deals with situations where both search filter and selection modes were turned on and screen was rotated.

Can't understand how ur solution deals with this scenario....where do u reapply the search filter after rotation?

**Comment by ShahoodulHassan** [comment]
@tcqq yeah let's hope @davideas responds sooner than later and fixes this.

**Comment by davideas** [comment]
@ShahoodulHassan, as experimented by removing the `configChange`, for basic use case the restoration of selection works as I programmed to work (without filter), also because the actionMode layout will cover the default android layout for filter; But if you add the filter use case you can clearly see that, the restoration of selected items occurs before the filter(async), so you will have positions selected that don't corresponds to the next filtered list (...and sometimes it crashes because of `IndexOutOfBoundsException: Inconsistency detected`).
Therefore, **we can't simply use both**, at least until I will move the selection as property of the adapter item. But, I don't know when and if I will do it.

⚠️ However, already with **medium lists**, it is not suggested to trigger the search again on screen rotation: due to the cost of the full operation: combination of _saving instance state, all object instantiation, retrieve original items, maybe showing headers, and finally the filter_. If your user is moving his arm (more times), it will trigger many times this sequence of these sub-operations.

Use the `configChanges` in this use case.
