### ISSUE TITLE
Solutions for light data

### ISSUE THREAD

**Issue by Spartak128** [davideas/FlexibleAdapter#672]
Hello,

First thank you very much for this library because you must have spent a lot of time to develop it. After comparing many solutions, I decided to integrate yours.

To populate the recyclerview, I currently fetch my data from the SQLite database, and put everything into an ArrayList.

```java
if (this.verbsCursor != null && this.verbsCursor.getCount() > 0) {
    this.verbsCursor.moveToPosition(-1);
    while (this.verbsCursor.moveToNext()){
        VerbItem vi = new VerbItem(getActivity(), new Verb(verbsCursor));
        data.add(vi);
    }
}
````

The Model (Verb) is separated from the FlexibleItem (VerbItem) to keep the Model clean and be able to manage it differently is different recyclerviews.

I then send my final ArrayList (data) to my CustomAdapter, which extends FlexibleAdapter.
this.adapter = new VerbsLearningListFlexibleAdapter(data);

The problem is that I have about 1500 items to load, and putting everything into an ArrayList is very slow. I was working with a cursor to do that before, and it was quite fast as I only needed to load items that were to be displayed. What is slow is not the recyclerview but preparing the data ArrayList.

However, checking your ASYNC example with big lists (10000 items), everything was loading fast, so I assumed it was possible. Reading your code, I saw that you generate quite easy objects (mainly String objects), and that might be why your example is so fast (I didn't test). But in real applications when we need full or light Entities, this approach takes much memory.

So I don't know your library quite well yet, I've already spent two days "playing" with it, and enjoyed the features so far. But I wanted to know if you had advice on how to tackle such problems with your library. I tried to created ValueObject out of my Verb items to get very light objects, it divided the calculation time by 3, but still was too long to be acceptable. I'd like to use your library in other parts of my app, but I do need to be able to load things quickly for a smooth user experience, and currently I don't see how I can do that. What approach would you suggest?

**Comment by davideas** [comment]
@Spartak128, this is always a dilemma because cursor doesn't allow to do advanced UI as this adapter has, but is fair for big list. For my logic I believe the solution in this case is only one, inspired by human eyes.
Let's pose 2 questions. 1) Since we have that small screen, does the user need to see all the items on screen simultaneously? We know that answer to the first question is no, so this opens to the second question, 2) how do we load more and more data?

I propose 2 solutions:
- One is loading more / infine scroll (based of user actions) with non-small threshold.
- Load and make available block of data repetitively in series (no need of user actions). This solution must give time to the RecyclerView to complete the insert notifications: 200-500ms should be enough (to verify!), then we repeat the loading more. Here, the trigger is the time not the scroll action.

From my point of view, loading so many data at once, is useless if user will see/need to see only a very little percentage of them. So why do we need to load everything then?

**Comment by Spartak128** [comment]
Thank you very much for your answer. So I understand I was not misusing your library, but it's actually a common technical issue, and I'd need to rethink the way I want to display my data.

Yes I agree, the main feature is a search tool, so as you said it might be useless to display the whole list at once. But if the user makes a search that with a constraint that still returns many items, the problem is the same, and then it would be a good idea to use your other propostions (infinite scroll / loading by blocks in the background).

For example if the user searches all verbs of a certain group, there might still be about 500 items, which might still be a little laggy on some older devices. So in such cases if I understand well, even after loading the 500 items, it would be better not to use the search/filter tool integrated to the FlexibleAdapter, but rather use a cursor in some cases to reload the required data into a new data ArrayList instead of filtering out all items one by one from the current ArrayList.

Thank you very much again for answering my question. I still want to update several parts of my app, and your answer is of great value to think about how I'll integrate the new features into the existing ones without sacrifying the interface smoothness.
