### ISSUE TITLE
How to keep the sticky header after filter items?

### ISSUE THREAD

**Issue by LuckHard** [davideas/FlexibleAdapter#73]
Hi davideas.

Thank you for creating this project.
I have some problems. Can you help me?
I want to keep the header after filter items (when empty result),how can i do?
In addition, may I have the results of the list before filter items?

Thanks.

**Comment by davideas** [comment]
Hello @LuckHard, I've added the functionality for header and items with header. I've committed something, I think it is not exactly what you are looking for when headers are sticky.
I have to disable the sticky headers during the search because the way how it is implemented (FrameLayout holding the itemView) at the RecyclerView doesn't like: _Two different ViewHolders have the same change ID. This might happen due to inconsistent Adapter update events or if the LayoutManager lays out the same View multiple times_. Which means no _sticky_ when filter is active.

I will however add the other improvement in the next SNAPSHOT release or in next pre-release when I am ready.

Regarding the possibility to have the results before the filter items, the only way to do it, is to duplicate the list as I suggested in the wiki: You have to pass a copy to the Adapter when you instantiate it, while during filter you have to pass the original list.
This is necessary because when user removes a character from the search text, the filter engine must search again from the bigger original list.

**Comment by davideas** [comment]
The implemented feature in available in v5.0.0-b6.

**Comment by LuckHard** [comment]
I'm sorry so long to reply. I tested it, it seems to work well,thanks a lot!
