### ISSUE TITLE
HeadersSectionInstagram layout jumps

### ISSUE THREAD

**Issue by yilzer** [davideas/FlexibleAdapter#76]
When i scroll down in the recyclerview ( scrolling from bottom to top slowly) the layout "jumps" at the point when a new header will be visible. I don't know if there is an solution for this bug or anything i could do to avoid this "jump". 

Thanks in advance

**Comment by davideas** [comment]
@yilzer, I cannot reproduce it, can you be more specific maybe showing a video?
I don't see any jumps in the Instagram header demo.

**Comment by yilzer** [comment]
Hi, I found the bug it was not in your code i used images in recyclerview with different sizes what caused this bug. However i've a new question for you in your example "instagram headers" it's easy to setup and load images into the recyclerview and create a feed, but one thing is hard to understand for me is to save data into the feed. In an regular recyclerview i save data into my custom object for example: 

public class CustomObject extends Parcable {
private boolean isLiked;

public CustomOBject(boolean isLiked){

public boolean isLiked(){
return isLiked;

public boolean setLiked(Boolean Liked){
this.IsLiked = Liked; // this part is not possible in your concept i don't know if there is an solution for this so i could use your library instead of another one which is easier to save data.

**Comment by davideas** [comment]
Hello @yilzer, thanks for the last message.
I still don't get it well:
- You can't use setLiked() ? why you say it's not possible? Every data can be saved in these items and used by the Adapter too.
- Or because it extends Parcelable? If so, you can create your own object implementing `IFlexible` interface OR you don't use the item interfaces at all but the normal way OR you can use the `IHolder` solution.

**Comment by yilzer** [comment]
Thanks for your quick response. I'm quite new to android so i didn't know it was possible in your adapter. I understand the way your adapter works much better know. I've just one more question for you:) Is it possible to save IFlexible items, (ArrayList<IFlexible> list) ,in onsaveInstance and retrieve in later in oncreate? If it is possible could you write a few lines of how this works?

Thanks in advance.

**Comment by davideas** [comment]
@yilzer, normally the original list should not be provided to the Adapter and the Adapter should manage a copy of that list because of internal changes, I explained this in the wiki pages.

The original list should be always available in memory, for example in a Singleton or in a local Database (for instance, you don't download again that list from remote), the copied list for the Adapter doesn't copy the objects but only the references so that we can create many list of the same objects.
In this way we don't need to save the original list in the onSaveInstance.

**Comment by yilzer** [comment]
Thanks man, we could close this question for now!
