### ISSUE TITLE
[5.0.0-b6] Possible filterItems() bug/corner case 

### ISSUE THREAD

**Issue by francescopedronomnys** [davideas/FlexibleAdapter#85]
Hello,
I could have spotted a bug/corner case in filterItems() method when list items have a very permissive equals() method or if they do not have one at all.

This is the equal method I'm using for a particular item class that is shown only a time on my list:
```
@Override
public boolean equals(Object inObject) {
    return inObject instanceof CategoryVideoArticlesItem;
}
```

I'm aware that you stated many times that items should have a good equals() method, but this corner case was very hard to spot for me, so maybe this issue could help someone else.

If one of these items were previously removed from the adapter (e.g. I'm using removeItemsOfType() method) and then reinserted they will not be shown in the filtered list even if they're filter() method matches.
This is because of this code in filterItems() method in FlexibleAdapter class:

```
if (filterExpandableObject(item, getSearchText())) {
    RestoreInfo restoreInfo = getPendingRemovedItem(item);
    if (restoreInfo != null) {
        //If found point to the new reference while filtering
        restoreInfo.filterRefItem = ++newOriginalPosition < values.size() ? values.get(newOriginalPosition) : null;
    } else {
        if (hasHeader(item) && !values.contains(getHeaderOf(item))) {
            values.add((T) getHeaderOf(item));
        }
        values.add(item);
        [...]
```

Here getPendingRemovedItem() restore items with a weak equals() method and does not insert them in the values List.

As a workaround after every removeItemsOfType() and consequent addItem() I've added an emptyBin() call.

**Comment by davideas** [comment]
@francescopedronomnys, if the items are deleted with restore functionality and filter is started just after, those items are not selected, if undo is pressed, they should appear in the current filter if the match returns true.
The initial `restoreInfo` is done to avoid to show the just deleted items during filter.

Indeed, the equals with only `instanceof` is not good at all.
Instead of calling emptyBin, which is automatically called after the undo timeout, you can set permanent deletion and no restoreInfo are created.

**Comment by davideas** [comment]
@francescopedronomnys, this issue is related to the `equals` method not well explained to be properly overridden and so it doesn't have any effect, during filtering for instance? basically, it doesn't have any effect in any operation (add/deletion/etc..).
Or it's a possible bug in the filtering? because I don't see bugs in filtering if equals is well implemented.

Just to understand.
Thanks.

**Comment by francescopedronomnys** [comment]
@davideas it seems to be a corner case of the usage of a weak equals method, not a bug but maybe something to point out in the wiki because it is very hard to spot.

**Comment by davideas** [comment]
Ok grazie.
